import { IsArray, IsBoolean, IsDateString, IsEnum, IsNumber, IsOptional, IsString, Min, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { SalesImportSource, SalesImportStatus, SalesImportTrigger } from '../entities/sales-ingestion.entity';

export class SalesRecordInputDto { @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() marketplace?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() currency?: string; @IsOptional() @IsString() timezone?: string; @IsDateString() saleDate: string; @IsOptional() @IsDateString() reportingDate?: string; @IsOptional() @IsString() bookId?: string; @IsOptional() @IsString() editionId?: string; @IsOptional() @IsString() format?: string; @IsNumber() @Min(0) quantity: number; @IsNumber() grossAmount: number; @IsOptional() @IsNumber() netAmount?: number; @IsOptional() @IsNumber() taxAmount?: number; @IsOptional() @IsNumber() discountAmount?: number; @IsOptional() @IsString() transactionId?: string; @IsOptional() @IsString() externalReference?: string; @IsOptional() metadata?: Record<string, unknown> }
export class ImportSalesDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsEnum(SalesImportSource) source: SalesImportSource; @IsOptional() @IsEnum(SalesImportTrigger) trigger?: SalesImportTrigger; @IsOptional() @IsString() fileName?: string; @IsOptional() @IsString() fileHash?: string; @IsArray() @ValidateNested({ each: true }) @Type(() => SalesRecordInputDto) records: SalesRecordInputDto[]; @IsOptional() @IsString() idempotencyKey?: string }
export class UploadSalesFileDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsString() fileName: string; @IsString() fileHash: string; @IsEnum(SalesImportSource) source: SalesImportSource; @IsString() content: string }
export class SyncSalesDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsBoolean() incremental?: boolean; @IsOptional() @IsDateString() since?: string }
export class SalesImportQueryDto { @IsOptional() @IsString() providerKey?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() bookId?: string; @IsOptional() @IsString() importId?: string; @IsOptional() @IsEnum(SalesImportStatus) status?: SalesImportStatus; @IsOptional() @Type(() => Number) @Min(1) page = 1; @IsOptional() @Type(() => Number) @Min(1) limit = 25 }
