import { createHash, randomUUID } from 'crypto';
import { Injectable } from '@nestjs/common';
import { salesRoyaltyNormalizationDefaultPolicy } from './config/sales-royalty-normalization.config';
import { BookEditionResolutionService } from './book-edition-resolution.service';
import { CanonicalRoyaltyRepository } from './canonical-royalty.repository';
import { CanonicalSalesRepository } from './canonical-sales.repository';
import { CountryNormalizationService } from './country-normalization.service';
import { CurrencyNormalizationService } from './currency-normalization.service';
import { CanonicalRoyaltyType, NormalizationEventType, NormalizationRecordStatus, NormalizationScope } from './entities/sales-royalty-normalization.entity';
import { FinancialValueNormalizer } from './financial-value.normalizer';
import { FormatNormalizationService } from './format-normalization.service';
import { MarketplaceNormalizationService } from './marketplace-normalization.service';
import { NormalizationConflictResolver } from './normalization-conflict.resolver';
import { NormalizationEventPublisher } from './normalization-event.publisher';
import { NormalizationResultRepository } from './normalization.repository';
import { NormalizationStrategyFactory } from './normalization-strategy.factory';
import { NormalizationValidator } from './normalization-validator';
import { ProviderMappingResolver } from './provider-mapping.resolver';
import { TimezoneNormalizationService } from './timezone-normalization.service';

@Injectable()
export class SalesRoyaltyNormalizationEngine {
  constructor(private readonly sales: CanonicalSalesRepository, private readonly royalties: CanonicalRoyaltyRepository, private readonly results: NormalizationResultRepository, private readonly mappings: ProviderMappingResolver, private readonly marketplace: MarketplaceNormalizationService, private readonly country: CountryNormalizationService, private readonly currency: CurrencyNormalizationService, private readonly timezone: TimezoneNormalizationService, private readonly format: FormatNormalizationService, private readonly books: BookEditionResolutionService, private readonly money: FinancialValueNormalizer, private readonly strategy: NormalizationStrategyFactory, private readonly conflicts: NormalizationConflictResolver, private readonly validator: NormalizationValidator, private readonly events: NormalizationEventPublisher) {}
  async normalizeSalesRecord(batchId: string, source: Record<string, unknown>, userId?: string) {
    this.validator.validateSource(source); const providerKey = String(source.providerKey); const profile = this.mappings.resolve(providerKey); const sourceRecordId = String(source._id ?? source.salesRecordId ?? randomUUID()); const sourceFingerprint = String(source.importFingerprint ?? this.fingerprint(source)); const book = this.books.resolve({ projectId: String(source.projectId ?? ''), bookId: source.bookId as string | null, editionId: source.editionId as string | null, format: source.format as string | null }); const timezone = this.timezone.normalize(source.timezone as string | null); const saleDate = new Date(source.saleDate as string | Date); const reportingDate = new Date((source.reportingDate ?? source.saleDate) as string | Date); const canonicalFingerprint = this.fingerprint({ providerKey, sourceFingerprint, profile: profile.profileVersion, bookId: book.bookId, editionId: book.editionId, date: saleDate.toISOString(), amount: source.netAmount, quantity: source.quantity });
    const existing = await this.sales.findByCanonicalFingerprint(canonicalFingerprint); const conflicts = this.conflicts.detect(existing, canonicalFingerprint); if (existing && salesRoyaltyNormalizationDefaultPolicy.duplicatePolicy === 'RETURN_EXISTING') return this.result(batchId, NormalizationScope.SALES, source, sourceRecordId, sourceFingerprint, String(existing._id), canonicalFingerprint, NormalizationRecordStatus.DUPLICATE, book, profile, conflicts, userId);
    const created = await this.sales.create({ canonicalSalesId: `CSL-${randomUUID()}`, projectId: book.projectId, bookId: book.bookId, editionId: book.editionId, providerKey, providerAccountId: null, marketplaceId: this.marketplace.normalize(source.marketplace as string | null), countryCode: this.country.normalize(source.country as string | null), territoryCode: null, currencyCode: this.currency.normalize(source.currency as string | null), transactionCurrencyCode: this.currency.normalize(source.currency as string | null), timezone, transactionType: this.strategy.transactionType(source.transactionType as string | null), saleDate, saleDateUtc: this.timezone.toUtc(saleDate, timezone), reportingDate, reportingDateUtc: this.timezone.toUtc(reportingDate, timezone), format: this.format.normalize(source.format as string | null), quantity: Number(source.quantity ?? 0), grossAmount: this.money.money(source.grossAmount as number | string), discountAmount: this.money.money(source.discountAmount as number | string), taxAmount: this.money.money(source.taxAmount as number | string), refundAmount: this.money.money(source.refundAmount as number | string), netAmount: this.money.money(source.netAmount as number | string), unitPrice: this.money.unitPrice(source.netAmount as number | string, Number(source.quantity ?? 0)), exchangeRate: null, baseCurrencyCode: null, baseCurrencyGrossAmount: null, baseCurrencyNetAmount: null, providerTransactionId: source.transactionId as string | null, externalReference: source.externalReference as string | null, sourceImportId: String(source.importId), sourceRecordId, sourceFingerprint, canonicalFingerprint, mappingProfileId: salesRoyaltyNormalizationDefaultPolicy.defaultMappingProfileId, mappingProfileVersion: profile.profileVersion, normalizedAt: new Date(), normalizationStatus: NormalizationRecordStatus.NORMALIZED, metadata: this.sanitize(source.metadata as Record<string, unknown> ?? {}), lineage: { source, mappingProfileVersion: profile.profileVersion }, createdBy: userId ?? null, updatedBy: userId ?? null });
    this.events.publish(NormalizationEventType.SALES_RECORD_NORMALIZED, { batchId, canonicalRecordId: String(created._id) }); return this.result(batchId, NormalizationScope.SALES, source, sourceRecordId, sourceFingerprint, String(created._id), canonicalFingerprint, NormalizationRecordStatus.NORMALIZED, book, profile, [], userId);
  }
  async normalizeRoyaltyRecord(batchId: string, source: Record<string, unknown>, userId?: string) {
    this.validator.validateSource(source); const providerKey = String(source.providerKey); const profile = this.mappings.resolve(providerKey); const sourceRecordId = String(source._id ?? source.royaltyRecordId ?? randomUUID()); const sourceFingerprint = String(source.importFingerprint ?? this.fingerprint(source)); const book = this.books.resolve({ projectId: String(source.projectId ?? ''), bookId: source.bookId as string | null, editionId: source.editionId as string | null, format: source.format as string | null }); const period = this.period(String(source.royaltyPeriod ?? new Date().toISOString().slice(0, 7))); const reportingDate = new Date((source.reportingDate ?? period.start) as string | Date); const canonicalFingerprint = this.fingerprint({ providerKey, sourceFingerprint, profile: profile.profileVersion, bookId: book.bookId, editionId: book.editionId, period: source.royaltyPeriod, amount: source.royaltyAmount, payment: source.paymentAmount });
    const existing = await this.royalties.findByCanonicalFingerprint(canonicalFingerprint); const conflicts = this.conflicts.detect(existing, canonicalFingerprint); if (existing && salesRoyaltyNormalizationDefaultPolicy.duplicatePolicy === 'RETURN_EXISTING') return this.result(batchId, NormalizationScope.ROYALTY, source, sourceRecordId, sourceFingerprint, String(existing._id), canonicalFingerprint, NormalizationRecordStatus.DUPLICATE, book, profile, conflicts, userId);
    const royaltyType = this.strategy.royaltyType(source.royaltyType as string | null); const created = await this.royalties.create({ canonicalRoyaltyId: `CRY-${randomUUID()}`, projectId: book.projectId, bookId: book.bookId, editionId: book.editionId, providerKey, providerAccountId: null, marketplaceId: this.marketplace.normalize(source.marketplace as string | null), countryCode: this.country.normalize(source.country as string | null), territoryCode: null, currencyCode: this.currency.normalize(source.currency as string | null), paymentCurrencyCode: this.currency.normalize(source.currency as string | null), timezone: this.timezone.normalize(source.timezone as string | null), royaltyPeriodStart: period.start, royaltyPeriodEnd: period.end, reportingDate, paymentDate: source.paymentDate ? new Date(source.paymentDate as string | Date) : null, royaltyType, paymentStatus: this.strategy.paymentStatus(source.paymentStatus as string | null), estimated: Boolean(source.estimated ?? royaltyType === CanonicalRoyaltyType.ESTIMATED), finalized: Boolean(source.finalized ?? royaltyType === CanonicalRoyaltyType.FINAL), adjustment: royaltyType === CanonicalRoyaltyType.ADJUSTMENT, correction: royaltyType === CanonicalRoyaltyType.CORRECTION, format: this.format.normalize(source.format as string | null), unitsSold: Number(source.unitsSold ?? 0), grossRevenue: this.money.money(source.grossRevenue as number | string), eligibleRevenue: this.money.money(source.eligibleRevenue as number | string ?? source.grossRevenue as number | string), royaltyRate: this.money.money(source.royaltyRate as number | string), royaltyAmount: this.money.money(source.royaltyAmount as number | string), taxAmount: this.money.money(source.taxAmount as number | string), withholdingTax: this.money.money(source.withholdingTax as number | string), feesAmount: this.money.money(source.feesAmount as number | string), adjustmentAmount: this.money.money(source.adjustmentAmount as number | string), paymentAmount: this.money.money(source.paymentAmount as number | string), exchangeRate: null, baseCurrencyCode: null, baseCurrencyRoyaltyAmount: null, baseCurrencyPaymentAmount: null, providerTransactionId: source.transactionId as string | null, externalReference: source.externalReference as string | null, sourceImportId: String(source.importId), sourceRecordId, sourceFingerprint, canonicalFingerprint, mappingProfileId: salesRoyaltyNormalizationDefaultPolicy.defaultMappingProfileId, mappingProfileVersion: profile.profileVersion, normalizedAt: new Date(), normalizationStatus: NormalizationRecordStatus.NORMALIZED, metadata: this.sanitize(source.metadata as Record<string, unknown> ?? {}), lineage: { source, mappingProfileVersion: profile.profileVersion }, createdBy: userId ?? null, updatedBy: userId ?? null });
    this.events.publish(NormalizationEventType.ROYALTY_RECORD_NORMALIZED, { batchId, canonicalRecordId: String(created._id) }); return this.result(batchId, NormalizationScope.ROYALTY, source, sourceRecordId, sourceFingerprint, String(created._id), canonicalFingerprint, NormalizationRecordStatus.NORMALIZED, book, profile, [], userId);
  }
  private result(batchId: string, scope: NormalizationScope, source: Record<string, unknown>, sourceRecordId: string, sourceFingerprint: string, canonicalRecordId: string | null, canonicalFingerprint: string, status: NormalizationRecordStatus, book: { bookMatchStatus: string; editionMatchStatus: string }, profile: { profileVersion: string }, conflicts: Record<string, unknown>[], userId?: string) { return this.results.create({ normalizationResultId: `NRS-${randomUUID()}`, normalizationBatchId: batchId, scope, sourceImportId: String(source.importId), sourceRecordId, sourceFingerprint, canonicalRecordId, canonicalFingerprint, providerKey: String(source.providerKey), projectId: String(source.projectId ?? 'unmatched'), mappingProfileId: salesRoyaltyNormalizationDefaultPolicy.defaultMappingProfileId, mappingProfileVersion: profile.profileVersion, status, bookMatchStatus: book.bookMatchStatus as never, editionMatchStatus: book.editionMatchStatus as never, mappingsApplied: {}, warnings: [], errors: [], conflicts, attempt: 1, normalizedAt: new Date(), lineage: { sourceRecordId }, createdBy: userId ?? null, updatedBy: userId ?? null }); }
  private fingerprint(input: unknown): string { return createHash('sha256').update(JSON.stringify(input)).digest('hex'); }
  private sanitize(input: Record<string, unknown>): Record<string, unknown> { const sensitive = /token|secret|password|cookie|authorization|credential/i; return Object.fromEntries(Object.entries(input).filter(([key]) => !sensitive.test(key))); }
  private period(value: string): { start: Date; end: Date } { const start = new Date(value.length === 7 ? `${value}-01T00:00:00.000Z` : value); const end = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0, 23, 59, 59, 999)); return { start, end }; }
}
