import { Type } from 'class-transformer';
import { IsEnum, IsMongoId, IsNumber, IsOptional, IsString, Max, Min } from 'class-validator';
import { GooglePlayBooksChecklistStatus, GooglePlayBooksFileProcessingStatus, GooglePlayBooksFormat, GooglePlayBooksStatus } from '../entities/google-play-books.entity';

export class PrepareGooglePlayBooksPackageDto { @IsMongoId() workflowId: string; @IsMongoId() targetExecutionId: string; @IsMongoId() projectId: string; @IsString() manuscriptVersion: string; @IsEnum(GooglePlayBooksFormat) contentFormat: GooglePlayBooksFormat; @IsOptional() @IsString() createdBy?: string; }
export class UpdateGooglePlayBooksChecklistItemDto { @Type(() => Number) @IsNumber() @Min(1) sequence: number; @IsEnum(GooglePlayBooksChecklistStatus) completionStatus: GooglePlayBooksChecklistStatus; }
export class RecordGooglePlayBooksSubmissionDto { @IsOptional() @IsString() accountProfileReference?: string; @IsOptional() @IsString() externalBookReference?: string; @IsOptional() @IsString() isbn?: string; @IsOptional() @IsString() googleBookIdentifier?: string; @IsOptional() @IsString() statusMessage?: string; @IsOptional() @IsString() submittedBy?: string; }
export class UpdateGooglePlayBooksProcessingStatusDto { @IsEnum(GooglePlayBooksFileProcessingStatus) status: GooglePlayBooksFileProcessingStatus; @IsString() fileType: string; @IsOptional() @IsString() statusMessage?: string; @IsOptional() @IsString() recordedBy?: string; }
export class UpdateGooglePlayBooksStatusDto { @IsEnum(GooglePlayBooksStatus) status: GooglePlayBooksStatus; @IsOptional() @IsString() statusMessage?: string; @IsOptional() @IsString() publishedUrl?: string; @IsOptional() @IsString() recordedBy?: string; }
export class GooglePlayBooksQueryDto { @IsOptional() @IsMongoId() projectId?: string; @IsOptional() @IsString() targetExecutionId?: string; @IsOptional() @IsEnum(GooglePlayBooksStatus) status?: GooglePlayBooksStatus; @IsOptional() @Type(() => Number) @IsNumber() @Min(1) page = 1; @IsOptional() @Type(() => Number) @IsNumber() @Min(1) @Max(100) limit = 20; }
