import { Cog, Shield } from 'lucide-react';
import type { ReactElement } from 'react';
import type { DashboardDefinition, DashboardWidgetDefinition } from '@/features/analytics-dashboard/types';
import {
  ActiveWorkers,
  APIHealth,
  APIKeyStatus,
  ApplicationVersion,
  AnalyticsQueue,
  AuditSummary,
  BackgroundJobs,
  BackupStatus,
  ConfigurationStatus,
  EnvironmentInformation,
  ErrorSummary,
  FailedJobs,
  FeatureFlags,
  ImportQueue,
  LoginActivity,
  MaintenanceStatus,
  MarketplaceConnections,
  MarketplaceStatus,
  OperationalAlerts,
  OperationsDataFreshness,
  OpportunityOperationsQueue,
  AIInsightOperationsQueue,
  ProcessingStatistics,
  ProviderConnections,
  ProviderStatus,
  PublishingQueue,
  RecentOperations,
  RetryQueue,
  RolesPermissionsSummary,
  ScheduledJobs,
  SecurityEvents,
  StorageStatus,
  SynchronizationQueue,
  SystemNotifications,
  SystemOverview,
  UserSummaryAdmin,
  WorkspaceSummary,
} from './components/operations-admin-sections';

const operationalFilters: DashboardDefinition['supportedFilters'] = ['projectId', 'portfolioId', 'providerKeys', 'marketplaceIds', 'statuses', 'period', 'dateRange', 'search'];

const operationWidgets: Array<[string, string, DashboardWidgetDefinition['type'], DashboardWidgetDefinition['category'], (props: { filters: Parameters<typeof SystemOverview>[0]['filters'] }) => ReactElement]> = [
  ['OPERATIONS_SYSTEM_OVERVIEW', 'System Overview', 'KPI', 'OPERATIONS', SystemOverview],
  ['OPERATIONS_PUBLISHING_QUEUE', 'Publishing Queue', 'TABLE', 'OPERATIONS', PublishingQueue],
  ['OPERATIONS_IMPORT_QUEUE', 'Import Queue', 'TABLE', 'OPERATIONS', ImportQueue],
  ['OPERATIONS_SYNCHRONIZATION_QUEUE', 'Synchronization Queue', 'TABLE', 'OPERATIONS', SynchronizationQueue],
  ['OPERATIONS_ANALYTICS_QUEUE', 'Analytics Queue', 'TABLE', 'OPERATIONS', AnalyticsQueue],
  ['OPERATIONS_OPPORTUNITY_QUEUE', 'Opportunity Queue', 'TABLE', 'OPERATIONS', OpportunityOperationsQueue],
  ['OPERATIONS_AI_INSIGHT_QUEUE', 'AI Insight Queue', 'TABLE', 'OPERATIONS', AIInsightOperationsQueue],
  ['OPERATIONS_BACKGROUND_JOBS', 'Background Jobs', 'TABLE', 'OPERATIONS', BackgroundJobs],
  ['OPERATIONS_FAILED_JOBS', 'Failed Jobs', 'ALERT', 'OPERATIONS', FailedJobs],
  ['OPERATIONS_RETRY_QUEUE', 'Retry Queue', 'TABLE', 'OPERATIONS', RetryQueue],
  ['OPERATIONS_ACTIVE_WORKERS', 'Active Workers', 'HEALTH', 'OPERATIONS', ActiveWorkers],
  ['OPERATIONS_PROVIDER_STATUS', 'Provider Status', 'HEALTH', 'OPERATIONS', ProviderStatus],
  ['OPERATIONS_MARKETPLACE_STATUS', 'Marketplace Status', 'HEALTH', 'OPERATIONS', MarketplaceStatus],
  ['OPERATIONS_API_HEALTH', 'API Health', 'HEALTH', 'OPERATIONS', APIHealth],
  ['OPERATIONS_STORAGE_STATUS', 'Storage Status', 'HEALTH', 'OPERATIONS', StorageStatus],
  ['OPERATIONS_PROCESSING_STATISTICS', 'Processing Statistics', 'KPI', 'OPERATIONS', ProcessingStatistics],
  ['OPERATIONS_ERROR_SUMMARY', 'Error Summary', 'ALERT', 'OPERATIONS', ErrorSummary],
  ['OPERATIONS_ALERTS', 'Operational Alerts', 'ALERT', 'OPERATIONS', OperationalAlerts],
  ['OPERATIONS_RECENT_OPERATIONS', 'Recent Operations', 'ACTIVITY', 'OPERATIONS', RecentOperations],
  ['OPERATIONS_DATA_FRESHNESS', 'Data Freshness', 'HEALTH', 'OPERATIONS', OperationsDataFreshness],
];

const adminWidgets: Array<[string, string, DashboardWidgetDefinition['type'], DashboardWidgetDefinition['category'], (props: { filters: Parameters<typeof SystemOverview>[0]['filters'] }) => ReactElement]> = [
  ['ADMIN_USER_SUMMARY', 'User Summary', 'KPI', 'ADMINISTRATION', UserSummaryAdmin],
  ['ADMIN_ROLES_PERMISSIONS', 'Roles & Permissions Summary', 'HEALTH', 'ADMINISTRATION', RolesPermissionsSummary],
  ['ADMIN_WORKSPACE_SUMMARY', 'Workspace Summary', 'KPI', 'ADMINISTRATION', WorkspaceSummary],
  ['ADMIN_API_KEY_STATUS', 'API Key Status', 'HEALTH', 'ADMINISTRATION', APIKeyStatus],
  ['ADMIN_PROVIDER_CONNECTIONS', 'Provider Connections', 'HEALTH', 'ADMINISTRATION', ProviderConnections],
  ['ADMIN_MARKETPLACE_CONNECTIONS', 'Marketplace Connections', 'HEALTH', 'ADMINISTRATION', MarketplaceConnections],
  ['ADMIN_CONFIGURATION_STATUS', 'Configuration Status', 'HEALTH', 'ADMINISTRATION', ConfigurationStatus],
  ['ADMIN_FEATURE_FLAGS', 'Feature Flags', 'HEALTH', 'ADMINISTRATION', FeatureFlags],
  ['ADMIN_AUDIT_SUMMARY', 'Audit Summary', 'KPI', 'ADMINISTRATION', AuditSummary],
  ['ADMIN_SECURITY_EVENTS', 'Security Events', 'ALERT', 'ADMINISTRATION', SecurityEvents],
  ['ADMIN_LOGIN_ACTIVITY', 'Login Activity', 'ACTIVITY', 'ADMINISTRATION', LoginActivity],
  ['ADMIN_SYSTEM_NOTIFICATIONS', 'System Notifications', 'ALERT', 'ADMINISTRATION', SystemNotifications],
  ['ADMIN_SCHEDULED_JOBS', 'Scheduled Jobs', 'TABLE', 'ADMINISTRATION', ScheduledJobs],
  ['ADMIN_BACKUP_STATUS', 'Backup Status', 'HEALTH', 'ADMINISTRATION', BackupStatus],
  ['ADMIN_MAINTENANCE_STATUS', 'Maintenance Status', 'HEALTH', 'ADMINISTRATION', MaintenanceStatus],
  ['ADMIN_APPLICATION_VERSION', 'Application Version', 'HEALTH', 'ADMINISTRATION', ApplicationVersion],
  ['ADMIN_ENVIRONMENT_INFORMATION', 'Environment Information', 'HEALTH', 'ADMINISTRATION', EnvironmentInformation],
];

function createWidgets(rows: typeof operationWidgets, dashboardKey: 'operations-dashboard' | 'administration-dashboard', requiredPermissions: string[]): DashboardWidgetDefinition[] {
  return rows.map(([key, title, type, category, Component]) => ({
    key,
    title,
    type,
    category,
    requiredPermissions,
    supportedDashboards: [dashboardKey],
    supportedScopes: ['PORTFOLIO', 'PROJECT'],
    queryDefinition: { queryKeyBase: key },
    defaultSize: { columns: key.endsWith('OVERVIEW') || key.endsWith('SUMMARY') ? 12 : 6, rows: 3 },
    minimumSize: { columns: 4, rows: 2 },
    refreshBehavior: 'INHERIT',
    exportCapabilities: ['CSV'],
    version: 1,
    render: ({ filters }) => <Component filters={filters} />,
  }));
}

export const operationsDashboardWidgets = createWidgets(operationWidgets, 'operations-dashboard', ['operations:read']);
export const administrationDashboardWidgets = createWidgets(adminWidgets, 'administration-dashboard', ['admin']);

export const operationsDashboardDefinition: DashboardDefinition = {
  key: 'operations-dashboard',
  route: '/analytics/operations',
  title: 'Operations Dashboard',
  description: 'Operational visibility across system health, publishing workflows, data pipelines, integrations and background processing.',
  icon: Cog,
  category: 'OPERATIONS',
  order: 110,
  enabled: true,
  featureFlag: 'operationsDashboard',
  requiredPermissions: ['operations:read'],
  supportedScopes: ['PORTFOLIO', 'PROJECT'],
  defaultScope: 'PORTFOLIO',
  supportedFilters: operationalFilters,
  defaultFilters: { scope: 'PORTFOLIO', period: 'LAST_30_DAYS' },
  supportedPeriods: ['TODAY', 'YESTERDAY', 'LAST_7_DAYS', 'LAST_30_DAYS', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD'],
  defaultComparisonMode: 'NONE',
  widgetDefinitions: operationsDashboardWidgets,
  layoutDefinition: { columns: 12, items: operationsDashboardWidgets.map((widget, index) => ({ widgetKey: widget.key, colSpan: index === 0 ? 12 : 6, order: index + 1 })) },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
};

export const administrationDashboardDefinition: DashboardDefinition = {
  key: 'administration-dashboard',
  route: '/analytics/administration',
  title: 'Administration Dashboard',
  description: 'Administrative visibility for users, permissions, configuration, security, audit, scheduled jobs and environment metadata.',
  icon: Shield,
  category: 'ADMINISTRATION',
  order: 120,
  enabled: true,
  featureFlag: 'administrationDashboard',
  requiredPermissions: ['admin'],
  supportedScopes: ['PORTFOLIO', 'PROJECT'],
  defaultScope: 'PORTFOLIO',
  supportedFilters: operationalFilters,
  defaultFilters: { scope: 'PORTFOLIO', period: 'LAST_30_DAYS' },
  supportedPeriods: ['TODAY', 'YESTERDAY', 'LAST_7_DAYS', 'LAST_30_DAYS', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD'],
  defaultComparisonMode: 'NONE',
  widgetDefinitions: administrationDashboardWidgets,
  layoutDefinition: { columns: 12, items: administrationDashboardWidgets.map((widget, index) => ({ widgetKey: widget.key, colSpan: index === 0 || index === 2 || index === 8 ? 12 : 6, order: index + 1 })) },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
};
