import { UserRound } from 'lucide-react';
import type { DashboardDefinition, DashboardWidgetDefinition } from '@/features/analytics-dashboard/types';
import { platformDefaults } from '@/features/platform-registry';
import {
  ContinueWorking,
  DashboardFreshness,
  Favorites,
  MyAIInsights,
  MyAlerts,
  MyBooks,
  MyKPIs,
  MyOpportunities,
  QuickActions,
  RecentActivity,
  RecentAnalytics,
  RecentImports,
  RecentSyncs,
  UserDashboardSummary,
} from './components/user-dashboard-sections';

export const userDashboardWidgets: DashboardWidgetDefinition[] = [
  { key: 'USER_SUMMARY', type: 'KPI', title: 'User Summary', category: 'OVERVIEW', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-summary' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <UserDashboardSummary filters={filters} /> },
  { key: 'USER_KPIS', type: 'KPI', title: 'My KPIs', category: 'PERFORMANCE', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-kpis' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 12, rows: 1 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <MyKPIs filters={filters} /> },
  { key: 'USER_BOOKS', type: 'TABLE', title: 'My Books', category: 'CONTENT', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-books' }, defaultSize: { columns: 8, rows: 3 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <MyBooks filters={filters} /> },
  { key: 'USER_CONTINUE_WORKING', type: 'ACTIVITY', title: 'Continue Working', category: 'CONTENT', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-continue-working' }, defaultSize: { columns: 4, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: [], version: 1, render: ({ filters }) => <ContinueWorking filters={filters} /> },
  { key: 'USER_FAVORITES', type: 'ACTIVITY', title: 'Favorites', category: 'CONTENT', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-favorites' }, defaultSize: { columns: 4, rows: 2 }, minimumSize: { columns: 3, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: [], version: 1, render: ({ filters }) => <Favorites filters={filters} /> },
  { key: 'USER_RECENT_ACTIVITY', type: 'ACTIVITY', title: 'Recent Activity', category: 'OPERATIONS', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-recent-activity' }, defaultSize: { columns: 4, rows: 3 }, minimumSize: { columns: 3, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentActivity filters={filters} /> },
  { key: 'USER_RECENT_IMPORTS', type: 'ACTIVITY', title: 'Recent Imports', category: 'OPERATIONS', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-recent-imports' }, defaultSize: { columns: 4, rows: 3 }, minimumSize: { columns: 3, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentImports filters={filters} /> },
  { key: 'USER_RECENT_SYNCS', type: 'ACTIVITY', title: 'Recent Syncs', category: 'OPERATIONS', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-recent-syncs' }, defaultSize: { columns: 4, rows: 3 }, minimumSize: { columns: 3, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentSyncs filters={filters} /> },
  { key: 'USER_RECENT_ANALYTICS', type: 'ACTIVITY', title: 'Recent Analytics', category: 'PERFORMANCE', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-recent-analytics' }, defaultSize: { columns: 4, rows: 3 }, minimumSize: { columns: 3, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentAnalytics filters={filters} /> },
  { key: 'USER_OPPORTUNITIES', type: 'OPPORTUNITY', title: 'My Opportunities', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-opportunities' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'MANUAL', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <MyOpportunities filters={filters} /> },
  { key: 'USER_AI_INSIGHTS', type: 'INSIGHT', title: 'My AI Insights', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-ai-insights' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'MANUAL', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <MyAIInsights filters={filters} /> },
  { key: 'USER_ALERTS', type: 'ALERT', title: 'My Alerts', category: 'OPERATIONS', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-alerts' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <MyAlerts filters={filters} /> },
  { key: 'USER_QUICK_ACTIONS', type: 'CUSTOM', title: 'Quick Actions', category: 'OVERVIEW', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-quick-actions', enabled: false }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 1 }, refreshBehavior: 'INHERIT', exportCapabilities: [], version: 1, render: ({ filters }) => <QuickActions filters={filters} /> },
  { key: 'USER_DATA_FRESHNESS', type: 'HEALTH', title: 'Dashboard Freshness', category: 'OPERATIONS', supportedDashboards: ['user-dashboard'], supportedScopes: ['USER'], queryDefinition: { queryKeyBase: 'user-data-freshness' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <DashboardFreshness filters={filters} /> },
];

export const userDashboardDefinition: DashboardDefinition = {
  key: 'user-dashboard',
  route: '/analytics/user',
  title: 'User Dashboard',
  description: 'A personalized workspace for publishing work, portfolio activity, opportunities, AI recommendations, alerts, and recent analytics.',
  icon: UserRound,
  category: 'OVERVIEW',
  order: 30,
  enabled: true,
  featureFlag: 'userDashboard',
  requiredPermissions: ['analytics:read'],
  supportedScopes: ['USER'],
  defaultScope: 'USER',
  supportedFilters: ['period', 'dateRange', 'comparisonMode', 'comparisonDateRange', 'currencyCode', 'projectId', 'portfolioId', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats', 'search'],
  defaultFilters: { scope: 'USER', period: 'LAST_30_DAYS', comparisonMode: 'PREVIOUS_PERIOD', currencyCode: platformDefaults.reportingCurrency },
  supportedPeriods: ['TODAY', 'YESTERDAY', 'LAST_7_DAYS', 'LAST_30_DAYS', 'LAST_90_DAYS', 'CURRENT_MONTH', 'CURRENT_YEAR', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD', 'PREVIOUS_CALENDAR_PERIOD', 'PREVIOUS_YEAR', 'CUSTOM'],
  defaultComparisonMode: 'PREVIOUS_PERIOD',
  supportedCurrencies: platformDefaults.supportedCurrencies,
  widgetDefinitions: userDashboardWidgets,
  layoutDefinition: {
    columns: 12,
    density: 'COMFORTABLE',
    minWidgetHeight: 160,
    items: [
      { widgetKey: 'USER_SUMMARY', colSpan: 12, order: 1 },
      { widgetKey: 'USER_KPIS', colSpan: 12, order: 2 },
      { widgetKey: 'USER_QUICK_ACTIONS', colSpan: 12, order: 3 },
      { widgetKey: 'USER_BOOKS', colSpan: 8, order: 4 },
      { widgetKey: 'USER_CONTINUE_WORKING', colSpan: 4, order: 5 },
      { widgetKey: 'USER_FAVORITES', colSpan: 4, order: 6 },
      { widgetKey: 'USER_RECENT_ACTIVITY', colSpan: 4, order: 7 },
      { widgetKey: 'USER_RECENT_ANALYTICS', colSpan: 4, order: 8 },
      { widgetKey: 'USER_OPPORTUNITIES', colSpan: 6, order: 9 },
      { widgetKey: 'USER_AI_INSIGHTS', colSpan: 6, order: 10 },
      { widgetKey: 'USER_ALERTS', colSpan: 6, order: 11 },
      { widgetKey: 'USER_RECENT_IMPORTS', colSpan: 6, order: 12 },
      { widgetKey: 'USER_RECENT_SYNCS', colSpan: 6, order: 13 },
      { widgetKey: 'USER_DATA_FRESHNESS', colSpan: 6, order: 14 },
    ],
  },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
  metadata: { domain: 'user-workspace', supportsFavorites: true, supportsPinnedEntities: true },
};
