import type { BookMatchStatus, CanonicalFormat, CanonicalPaymentStatus, CanonicalRoyaltyType, CanonicalTransactionType, NormalizationRecordStatus, NormalizationScope } from '../entities/sales-royalty-normalization.entity';

export interface NormalizationRequest { scope: NormalizationScope; projectId?: string; providerKey?: string; importIds?: string[]; sourceRecordId?: string; from?: Date; to?: Date; reprocessingReason?: string; correlationId?: string }
export interface BookResolutionResult { projectId: string; bookId: string | null; editionId: string | null; bookMatchStatus: BookMatchStatus; editionMatchStatus: BookMatchStatus; evidence: Record<string, unknown> }
export interface DimensionResolutionResult { providerKey: string; marketplaceId: string; countryCode: string; territoryCode: string | null; currencyCode: string; timezone: string; languageCode?: string | null; format: CanonicalFormat; mappingsApplied: Record<string, unknown>; warnings: string[] }
export interface FinancialNormalizationResult { amount: string; baseAmount: string | null; currencyCode: string; baseCurrencyCode: string | null; exchangeRate: string | null; warnings: string[] }
export interface NormalizationOutcome { status: NormalizationRecordStatus; canonicalRecordId?: string | null; canonicalFingerprint?: string | null; warnings: string[]; errors: Record<string, unknown>[]; conflicts: Record<string, unknown>[] }
export interface CanonicalSalesInput { projectId: string; bookId: string | null; editionId: string | null; providerKey: string; marketplaceId: string; countryCode: string; territoryCode: string | null; currencyCode: string; transactionCurrencyCode: string; timezone: string; transactionType: CanonicalTransactionType; saleDate: Date; saleDateUtc: Date; reportingDate: Date; reportingDateUtc: Date; format: CanonicalFormat; quantity: number; grossAmount: string; discountAmount: string; taxAmount: string; refundAmount: string; netAmount: string; unitPrice: string | null; providerTransactionId: string | null; externalReference: string | null; sourceImportId: string; sourceRecordId: string; sourceFingerprint: string; metadata: Record<string, unknown>; lineage: Record<string, unknown> }
export interface CanonicalRoyaltyInput { projectId: string; bookId: string | null; editionId: string | null; providerKey: string; marketplaceId: string; countryCode: string; territoryCode: string | null; currencyCode: string; paymentCurrencyCode: string; timezone: string; royaltyPeriodStart: Date; royaltyPeriodEnd: Date; reportingDate: Date; paymentDate: Date | null; royaltyType: CanonicalRoyaltyType; paymentStatus: CanonicalPaymentStatus; estimated: boolean; finalized: boolean; adjustment: boolean; correction: boolean; format: CanonicalFormat; unitsSold: number; grossRevenue: string; eligibleRevenue: string; royaltyRate: string; royaltyAmount: string; taxAmount: string; withholdingTax: string; feesAmount: string; adjustmentAmount: string; paymentAmount: string; providerTransactionId: string | null; externalReference: string | null; sourceImportId: string; sourceRecordId: string; sourceFingerprint: string; metadata: Record<string, unknown>; lineage: Record<string, unknown> }
