import { IsBoolean, IsDateString, IsEnum, IsMongoId, IsOptional, IsString, IsUrl, Min } from 'class-validator';
import { Type } from 'class-transformer';
import { NormalizedPublicationStatus, ProviderSyncStatus, PublicationStatusConflictPolicy, PublicationStatusSource, PublicationSyncMode, PublicationSyncTriggerType } from '../entities/publication-status-sync.entity';

export class SyncPublicationStatusDto { @IsMongoId() targetExecutionId: string; @IsOptional() @IsEnum(PublicationSyncTriggerType) triggerType?: PublicationSyncTriggerType; @IsOptional() @IsEnum(PublicationSyncMode) syncMode?: PublicationSyncMode; @IsOptional() @IsString() idempotencyKey?: string; @IsOptional() @IsString() correlationId?: string; @IsOptional() @IsBoolean() reconciliation?: boolean }
export class BatchSyncPublicationStatusDto { @IsOptional() @IsString() workflowId?: string; @IsOptional() @IsString() orchestrationId?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() providerKey?: string; @IsOptional() @IsEnum(PublicationSyncTriggerType) triggerType?: PublicationSyncTriggerType }
export class ManualPublicationStatusDto { @IsEnum(NormalizedPublicationStatus) status: NormalizedPublicationStatus; @IsOptional() @IsString() statusMessage?: string; @IsOptional() @IsDateString() providerUpdatedAt?: string; @IsOptional() @IsString() externalSubmissionId?: string; @IsOptional() @IsString() externalPublicationId?: string; @IsOptional() @IsUrl({ require_tld: false }) publicationUrl?: string; @IsOptional() actionRequiredDetails?: Record<string, unknown>; @IsOptional() rejectionDetails?: Record<string, unknown>; @IsOptional() evidenceReferences?: string[]; @IsOptional() @IsString() correctionReason?: string; @IsOptional() @Min(0) expectedVersion?: number }
export class ResolvePublicationStatusConflictDto { @IsString() conflictId: string; @IsEnum(PublicationStatusConflictPolicy) policy: PublicationStatusConflictPolicy; @IsOptional() @IsString() note?: string }
export class PublicationStatusSyncQueryDto { @IsOptional() @IsString() targetExecutionId?: string; @IsOptional() @IsString() workflowId?: string; @IsOptional() @IsString() orchestrationId?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() providerKey?: string; @IsOptional() @IsEnum(ProviderSyncStatus) syncStatus?: ProviderSyncStatus; @IsOptional() @IsEnum(PublicationStatusSource) source?: PublicationStatusSource; @IsOptional() @Type(() => Number) @Min(1) page = 1; @IsOptional() @Type(() => Number) @Min(1) limit = 20 }
export class ReconcilePublicationStatusDto { @IsOptional() @IsString() targetExecutionId?: string; @IsOptional() @IsString() workflowId?: string; @IsOptional() @IsString() orchestrationId?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsBoolean() applySafeFixes?: boolean }
