import type { AnalyticsEntityAdapter } from './types';

const commonFilters = ['projectId', 'portfolioId', 'period', 'dateRange', 'comparisonMode', 'comparisonDateRange', 'currencyCode', 'search'] as const;

export const analyticsEntityAdapters: AnalyticsEntityAdapter[] = [
  { entityKey: 'BOOK_ANALYTICS', dashboardKey: 'book-analytics-dashboard', route: '/analytics/books', title: 'Book Analytics', description: 'Book-level performance across editions, providers, marketplaces, countries and formats.', supportedScopes: ['BOOK'], defaultScope: 'BOOK', filters: [...commonFilters, 'bookIds', 'editionIds', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'refunds'], trendSeries: ['sales', 'revenue', 'royalties'], breakdownDimensions: ['edition', 'provider', 'marketplace', 'country', 'format'], rankingOptions: ['editions', 'marketplaces', 'providers'], drillDownTargets: ['sales-dashboard', 'revenue-dashboard', 'opportunity-dashboard'] },
  { entityKey: 'EDITION_ANALYTICS', dashboardKey: 'edition-analytics-dashboard', route: '/analytics/editions', title: 'Edition Analytics', description: 'Edition-level performance, publication status, provider availability and format-specific metrics.', supportedScopes: ['EDITION'], defaultScope: 'EDITION', filters: [...commonFilters, 'bookIds', 'editionIds', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'refunds'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['provider', 'marketplace', 'country'], rankingOptions: ['marketplaces', 'providers'], drillDownTargets: ['book-analytics-dashboard', 'sales-dashboard'] },
  { entityKey: 'AUTHOR_ANALYTICS', dashboardKey: 'author-analytics-dashboard', route: '/analytics/authors', title: 'Author Analytics', description: 'Authored-book performance using backend analytics.', supportedScopes: ['AUTHOR'], defaultScope: 'AUTHOR', filters: [...commonFilters, 'authorIds', 'bookIds', 'seriesIds', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'activeBooks'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['book', 'series', 'marketplace', 'format'], rankingOptions: ['books', 'series'], drillDownTargets: ['book-analytics-dashboard', 'series-analytics-dashboard'] },
  { entityKey: 'SERIES_ANALYTICS', dashboardKey: 'series-analytics-dashboard', route: '/analytics/series', title: 'Series Analytics', description: 'Series performance, book contribution, release order and coverage gaps.', supportedScopes: ['SERIES'], defaultScope: 'SERIES', filters: [...commonFilters, 'seriesIds', 'authorIds', 'bookIds', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'activeBooks'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['book', 'edition', 'marketplace', 'format'], rankingOptions: ['books', 'editions'], drillDownTargets: ['book-analytics-dashboard'] },
  { entityKey: 'PROVIDER_ANALYTICS', dashboardKey: 'provider-analytics-dashboard', route: '/analytics/providers', title: 'Provider Analytics', description: 'Provider contribution, growth, catalog coverage, marketplace reach, refunds and freshness.', supportedScopes: ['PROVIDER'], defaultScope: 'PROVIDER', filters: [...commonFilters, 'providerKeys', 'marketplaceIds', 'bookIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'refunds', 'activeBooks'], trendSeries: ['sales', 'revenue', 'refunds'], breakdownDimensions: ['book', 'marketplace', 'country', 'format'], rankingOptions: ['books', 'marketplaces'], drillDownTargets: ['sales-dashboard', 'revenue-dashboard'] },
  { entityKey: 'MARKETPLACE_ANALYTICS', dashboardKey: 'marketplace-analytics-dashboard', route: '/analytics/marketplaces', title: 'Marketplace Analytics', description: 'Marketplace contribution, growth, providers, countries, formats and active catalog.', supportedScopes: ['MARKETPLACE'], defaultScope: 'MARKETPLACE', filters: [...commonFilters, 'marketplaceIds', 'providerKeys', 'bookIds', 'countryCodes', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'activeBooks'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['provider', 'book', 'country', 'format'], rankingOptions: ['books', 'providers'], drillDownTargets: ['provider-analytics-dashboard', 'sales-dashboard'] },
  { entityKey: 'GEOGRAPHIC_ANALYTICS', dashboardKey: 'geographic-analytics-dashboard', route: '/analytics/geography', title: 'Geographic Analytics', description: 'Country and territory contribution, growth, coverage and rights-aware opportunities.', supportedScopes: ['COUNTRY', 'TERRITORY'], defaultScope: 'COUNTRY', filters: [...commonFilters, 'countryCodes', 'territoryCodes', 'providerKeys', 'marketplaceIds', 'bookIds', 'formats'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'activeBooks'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['country', 'territory', 'marketplace', 'provider', 'format'], rankingOptions: ['countries', 'books'], drillDownTargets: ['sales-dashboard', 'opportunity-dashboard'] },
  { entityKey: 'FORMAT_ANALYTICS', dashboardKey: 'format-analytics-dashboard', route: '/analytics/formats', title: 'Format Analytics', description: 'Performance and availability by configured publication formats.', supportedScopes: ['FORMAT'], defaultScope: 'FORMAT', filters: [...commonFilters, 'formats', 'bookIds', 'editionIds', 'providerKeys', 'marketplaceIds', 'countryCodes'], kpiKeys: ['sales', 'revenue', 'royalties', 'growth', 'activeEditions'], trendSeries: ['sales', 'revenue'], breakdownDimensions: ['format', 'book', 'provider', 'marketplace', 'country'], rankingOptions: ['formats', 'books'], drillDownTargets: ['book-analytics-dashboard', 'sales-dashboard'] },
];

export function getAnalyticsEntityAdapter(dashboardKey: string) {
  return analyticsEntityAdapters.find((adapter) => adapter.dashboardKey === dashboardKey || adapter.entityKey === dashboardKey);
}
