import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { AIWritingRepository } from '../ai-writing/ai-writing.repository';
import { BookMetadataRepository } from '../book-metadata/book-metadata.repository';
import { BookProjectService } from '../book-project/book-project.service';
import { ComplianceValidationRepository } from '../compliance-validation/compliance-validation.repository';
import { ComplianceValidationStatus, ComplianceValidationTargetType } from '../compliance-validation/entities/compliance-validation.entity';
import { ContentImprovementRepository } from '../content-improvement/content-improvement.repository';
import { ContentImprovementStatus } from '../content-improvement/entities/content-improvement.entity';
import { FactConsistencyStatus, FactConsistencyTargetType } from '../fact-consistency/entities/fact-consistency.entity';
import { FactConsistencyRepository } from '../fact-consistency/fact-consistency.repository';
import { PlagiarismDetectionStatus, PlagiarismRiskLevel, PlagiarismTargetType } from '../plagiarism-detection/entities/plagiarism-detection.entity';
import { PlagiarismDetectionRepository } from '../plagiarism-detection/plagiarism-detection.repository';
import { QualityIssueSeverity } from '../quality-review/entities/quality-review.entity';
import { QualityReviewRepository } from '../quality-review/quality-review.repository';
import { TableOfContentsRepository } from '../table-of-contents/table-of-contents.repository';
import { publicationReadinessPolicies } from './config/publication-readiness.config';
import type { CreatePublicationReadinessDto, PublicationReadinessQueryDto, RejectPublicationReadinessDto } from './dto';
import { ManualApprovalStatus, PublicationDecision, PublicationReadiness, PublicationReadinessDocument, PublicationReadinessStatus, ReadinessPolicyProfile, ReadinessRiskLevel, ReadinessTargetType } from './entities/publication-readiness.entity';
import type { ReadinessSourceRecord, ReadinessSources } from './interfaces/publication-readiness.interface';
import { PublicationReadinessEngine } from './publication-readiness.engine';
import { PublicationReadinessFactory } from './publication-readiness.factory';
import { PublicationReadinessMapper } from './publication-readiness.mapper';
import { PublicationReadinessRepository } from './publication-readiness.repository';
import { PublicationReadinessValidator } from './publication-readiness.validator';

@Injectable()
export class PublicationReadinessService {
  constructor(private readonly projects: BookProjectService, private readonly contents: AIWritingRepository, private readonly quality: QualityReviewRepository, private readonly improvements: ContentImprovementRepository, private readonly plagiarism: PlagiarismDetectionRepository, private readonly facts: FactConsistencyRepository, private readonly compliance: ComplianceValidationRepository, private readonly metadata: BookMetadataRepository, private readonly toc: TableOfContentsRepository, private readonly repository: PublicationReadinessRepository, private readonly engine: PublicationReadinessEngine, private readonly factory: PublicationReadinessFactory, private readonly validator: PublicationReadinessValidator, private readonly mapper: PublicationReadinessMapper) {}
  async create(dto: CreatePublicationReadinessDto) {
    await this.projects.findOne(dto.projectId); await this.validateTarget(dto);
    const policy = publicationReadinessPolicies[dto.policyProfile ?? ReadinessPolicyProfile.DEFAULT];
    if (await this.repository.findActiveAssessment(dto.targetType, dto.targetId, dto.manuscriptVersion, policy.policyVersion)) throw new ConflictException('Active publication readiness assessment already exists');
    const latest = await this.repository.latestAssessment(dto.projectId);
    const item = await this.repository.create({ assessmentId: `PENDING-${Date.now()}`, ...dto, policyProfile: policy.profile, policyVersion: policy.policyVersion, sourceResultIds: {}, sourceResultVersions: {}, overallScore: 0, qualityGateScore: 0, originalityGateScore: 0, factConsistencyGateScore: 0, complianceGateScore: 0, metadataGateScore: 0, structureGateScore: 0, exportGateScore: 0, riskLevel: ReadinessRiskLevel.NONE, finalDecision: PublicationDecision.NOT_READY, passedGates: [], failedGates: [], conditionalGates: [], blockers: [], warnings: [], recommendations: [], missingRequirements: [], manualApprovalRequired: policy.manualApprovalMandatory, manualApprovalStatus: policy.manualApprovalMandatory ? ManualApprovalStatus.REQUIRED : ManualApprovalStatus.NOT_REQUIRED, readyAt: null, approvedAt: null, approvedBy: null, rejectedAt: null, rejectedBy: null, rejectionReason: null, status: PublicationReadinessStatus.PENDING, readinessVersion: (latest?.readinessVersion ?? 0) + 1, isSuperseded: false, supersededBy: null, failureCode: null, failureMessage: null, isDeleted: false, createdBy: dto.createdBy ?? null, updatedBy: dto.createdBy ?? null });
    return this.mapper.toResponse(item);
  }
  async process(id: string) {
    const item = await this.document(id); this.validator.validateTransition(item.status, PublicationReadinessStatus.PROCESSING); await this.repository.update(id, { status: PublicationReadinessStatus.PROCESSING });
    try { const policy = publicationReadinessPolicies[item.policyProfile]; const sources = await this.resolveSources(item.projectId, item.targetType, item.targetId, item.manuscriptVersion); const result = this.engine.evaluate(sources, policy); const completed = this.factory.create({ projectId: item.projectId, targetType: item.targetType, targetId: item.targetId, manuscriptVersion: item.manuscriptVersion, scope: item.scope, readinessVersion: item.readinessVersion, createdBy: item.createdBy ?? undefined }, policy, result); return this.mapper.toResponse((await this.repository.update(id, completed))!); }
    catch (error) { await this.repository.update(id, { status: PublicationReadinessStatus.FAILED, failureCode: 'PUBLICATION_READINESS_FAILED', failureMessage: error instanceof Error ? error.message : 'Publication readiness assessment failed' }); throw error; }
  }
  async recalculate(id: string, userId?: string) {
    const previous = await this.document(id); const dto: CreatePublicationReadinessDto = { projectId: previous.projectId, targetType: previous.targetType, targetId: previous.targetId, scope: previous.scope, manuscriptVersion: previous.manuscriptVersion, policyProfile: previous.policyProfile, createdBy: userId ?? previous.createdBy ?? undefined };
    await this.repository.update(id, { status: PublicationReadinessStatus.SUPERSEDED, isSuperseded: true });
    const created = await this.createNewVersion(dto, previous.readinessVersion + 1);
    await this.repository.update(id, { supersededBy: String(created.id) });
    return this.process(String(created.id));
  }
  async approve(id: string, userId?: string) { const item = await this.document(id); this.validator.validateTransition(item.status, PublicationReadinessStatus.APPROVED); this.validator.validateApproval(item); return this.mapper.toResponse((await this.repository.update(id, { status: PublicationReadinessStatus.APPROVED, manualApprovalStatus: ManualApprovalStatus.APPROVED, approvedAt: new Date(), approvedBy: userId ?? null, updatedBy: userId ?? null }))!); }
  async reject(id: string, dto: RejectPublicationReadinessDto, userId?: string) { const item = await this.document(id); this.validator.validateTransition(item.status, PublicationReadinessStatus.REJECTED); return this.mapper.toResponse((await this.repository.update(id, { status: PublicationReadinessStatus.REJECTED, manualApprovalStatus: ManualApprovalStatus.REJECTED, rejectedAt: new Date(), rejectedBy: userId ?? null, rejectionReason: dto.reason ?? null, updatedBy: userId ?? null }))!); }
  async revokeApproval(id: string, userId?: string) { const item = await this.document(id); if (item.status !== PublicationReadinessStatus.APPROVED) throw new BadRequestException('Only approved assessments can be revoked'); return this.mapper.toResponse((await this.repository.update(id, { status: PublicationReadinessStatus.COMPLETED, manualApprovalStatus: item.manualApprovalRequired ? ManualApprovalStatus.REQUIRED : ManualApprovalStatus.REVOKED, approvedAt: null, approvedBy: null, updatedBy: userId ?? null }))!); }
  async findById(id: string) { return this.mapper.toResponse(await this.document(id)); }
  async findByProjectId(id: string) { return (await this.repository.findByProjectId(id)).map((item) => this.mapper.toResponse(item)); }
  async findByTarget(type: ReadinessTargetType, id: string) { return (await this.repository.findByTarget(type, id)).map((item) => this.mapper.toResponse(item)); }
  async latestAssessment(projectId: string, manuscriptVersion?: string) { const item = await this.repository.latestAssessment(projectId, manuscriptVersion); if (!item) throw new NotFoundException('Publication readiness assessment not found'); return this.mapper.toResponse(item); }
  async search(query: PublicationReadinessQueryDto) { const filter: FilterQuery<PublicationReadiness> = {}; if (query.projectId) filter.projectId = query.projectId; if (query.targetId) filter.targetId = query.targetId; if (query.manuscriptVersion) filter.manuscriptVersion = query.manuscriptVersion; if (query.policyProfile) filter.policyProfile = query.policyProfile; if (query.status) filter.status = query.status; if (query.finalDecision) filter.finalDecision = query.finalDecision; const result = await this.repository.paginate(filter, query.page, query.limit); return { ...result, items: result.items.map((item) => this.mapper.toResponse(item)) }; }
  async softDelete(id: string, userId?: string) { if (!(await this.repository.softDelete(id, userId))) throw new NotFoundException('Publication readiness assessment not found'); }
  async restore(id: string) { const item = await this.repository.restore(id); if (!item) throw new NotFoundException('Deleted publication readiness assessment not found'); return this.mapper.toResponse(item); }
  private async createNewVersion(dto: CreatePublicationReadinessDto, readinessVersion: number) { await this.validateTarget(dto); const policy = publicationReadinessPolicies[dto.policyProfile ?? ReadinessPolicyProfile.DEFAULT]; const item = await this.repository.create({ assessmentId: `PENDING-${Date.now()}`, ...dto, policyProfile: policy.profile, policyVersion: policy.policyVersion, sourceResultIds: {}, sourceResultVersions: {}, overallScore: 0, qualityGateScore: 0, originalityGateScore: 0, factConsistencyGateScore: 0, complianceGateScore: 0, metadataGateScore: 0, structureGateScore: 0, exportGateScore: 0, riskLevel: ReadinessRiskLevel.NONE, finalDecision: PublicationDecision.NOT_READY, passedGates: [], failedGates: [], conditionalGates: [], blockers: [], warnings: [], recommendations: [], missingRequirements: [], manualApprovalRequired: policy.manualApprovalMandatory, manualApprovalStatus: policy.manualApprovalMandatory ? ManualApprovalStatus.REQUIRED : ManualApprovalStatus.NOT_REQUIRED, readyAt: null, approvedAt: null, approvedBy: null, rejectedAt: null, rejectedBy: null, rejectionReason: null, status: PublicationReadinessStatus.PENDING, readinessVersion, isSuperseded: false, supersededBy: null, failureCode: null, failureMessage: null, isDeleted: false, createdBy: dto.createdBy ?? null, updatedBy: dto.createdBy ?? null }); return this.mapper.toResponse(item); }
  private async resolveSources(projectId: string, targetType: ReadinessTargetType, targetId: string, manuscriptVersion: string): Promise<ReadinessSources> {
    const [quality, plagiarism, fact, compliance, metadata, toc, improvements] = await Promise.all([this.quality.latestReview(projectId), this.plagiarism.findByTarget(PlagiarismTargetType.MANUSCRIPT, targetId), this.facts.findByTarget(FactConsistencyTargetType.MANUSCRIPT, targetId), this.compliance.findByTarget(targetType === ReadinessTargetType.BOOK ? ComplianceValidationTargetType.BOOK : ComplianceValidationTargetType.MANUSCRIPT, targetId), this.metadata.findByProjectId(projectId), this.toc.findByProjectId(projectId), this.improvements.findByProjectId(projectId)]);
    const sources: ReadinessSources = {};
    if (quality) { this.validator.validateVersion(manuscriptVersion, quality.reviewVersion); sources.QUALITY = this.source(String(quality._id), quality.reviewVersion, quality.status, quality.overallQualityScore, this.fromSeverity(quality.severity), quality.issues.filter((issue) => issue.severity === QualityIssueSeverity.CRITICAL).length, quality.issues.length, quality.issues.map((issue) => issue.message), quality.suggestions, quality.reviewVersion); }
    const plag = plagiarism.find((item) => item.projectId === projectId && item.manuscriptVersion === manuscriptVersion && [PlagiarismDetectionStatus.COMPLETED, PlagiarismDetectionStatus.APPROVED].includes(item.status));
    if (plag) sources.ORIGINALITY = this.source(String(plag._id), String(plag.detectionVersion), plag.status, plag.originalityScore, this.fromPlagiarismRisk(plag.riskLevel), plag.riskLevel === PlagiarismRiskLevel.CRITICAL || plag.publicationRecommendation === 'BLOCK' ? 1 : 0, plag.findings.length, plag.findings.map((finding) => finding.message), plag.recommendations, plag.manuscriptVersion);
    const factResult = fact.find((item) => item.projectId === projectId && item.manuscriptVersion === manuscriptVersion && [FactConsistencyStatus.COMPLETED, FactConsistencyStatus.APPROVED].includes(item.status));
    if (factResult) sources.FACT_CONSISTENCY = this.source(String(factResult._id), String(factResult.validationVersion), factResult.status, factResult.overallScore, factResult.riskLevel as unknown as ReadinessRiskLevel, factResult.contradictions.filter((issue) => issue.blockingPublication).length, [...factResult.contradictions, ...factResult.unsupportedClaims, ...factResult.citationIssues].length, [...factResult.contradictions, ...factResult.unsupportedClaims].map((issue) => issue.message), factResult.recommendations, factResult.manuscriptVersion);
    const comp = compliance.find((item) => item.projectId === projectId && item.manuscriptVersion === manuscriptVersion && [ComplianceValidationStatus.COMPLETED, ComplianceValidationStatus.APPROVED].includes(item.status));
    if (comp) { sources.COMPLIANCE = this.source(String(comp._id), String(comp.complianceVersion), comp.status, comp.overallScore, comp.blockingIssueCount ? ReadinessRiskLevel.CRITICAL : comp.warningCount ? ReadinessRiskLevel.LOW : ReadinessRiskLevel.NONE, comp.blockingIssueCount, comp.warningCount, comp.failedChecks.map((check) => check.message), comp.recommendations, comp.manuscriptVersion); sources.EXPORT = this.source(String(comp._id), String(comp.complianceVersion), comp.status, comp.exportReadinessScore, comp.exportReadinessScore < 60 ? ReadinessRiskLevel.HIGH : ReadinessRiskLevel.NONE, comp.failedChecks.filter((check) => check.category.includes('READINESS') || check.category.includes('EXPORT')).length, comp.warnings.filter((check) => check.category.includes('READINESS') || check.category.includes('EXPORT')).length, comp.failedChecks.map((check) => check.message), comp.recommendations, comp.manuscriptVersion); }
    if (metadata[0]) sources.METADATA = this.source(String(metadata[0]._id), String(metadata[0].metadataVersion), metadata[0].status, metadata[0].confidenceScore, metadata[0].title && metadata[0].shortDescription && metadata[0].longDescription ? ReadinessRiskLevel.NONE : ReadinessRiskLevel.HIGH, metadata[0].title && metadata[0].shortDescription && metadata[0].longDescription ? 0 : 1, 0, ['Metadata completeness evaluated'], [], manuscriptVersion);
    if (toc[0]) sources.STRUCTURE = this.source(String(toc[0]._id), String(toc[0].tocVersion), toc[0].status, toc[0].confidenceScore, toc[0].totalChapters > 0 ? ReadinessRiskLevel.NONE : ReadinessRiskLevel.HIGH, toc[0].totalChapters > 0 ? 0 : 1, 0, ['Table of contents structure evaluated'], [], manuscriptVersion);
    const improvement = improvements.find((item) => item.targetId === targetId || item.scope === 'MANUSCRIPT');
    if (improvement) sources.CONTENT_IMPROVEMENT = this.source(String(improvement._id), String(improvement.improvementVersion), improvement.status, improvement.status === ContentImprovementStatus.APPLIED ? 100 : improvement.status === ContentImprovementStatus.APPROVED ? 80 : 60, improvement.status === ContentImprovementStatus.APPLIED ? ReadinessRiskLevel.NONE : ReadinessRiskLevel.LOW, 0, improvement.unresolvedIssueIds.length, [improvement.improvementSummary], [], manuscriptVersion);
    sources.MANUAL_APPROVAL = this.source('manual-approval-policy', '1', 'COMPLETED', 100, ReadinessRiskLevel.NONE, 0, 0, ['Manual approval policy evaluated'], [], manuscriptVersion);
    return sources;
  }
  private source(id: string, version: string, status: string, score: number, riskLevel: ReadinessRiskLevel, blockerCount: number, warningCount: number, reasons: string[], recommendations: string[], manuscriptVersion: string): ReadinessSourceRecord { return { id, version, status, score, riskLevel, blockerCount, warningCount, reasons, recommendations, manuscriptVersion }; }
  private fromSeverity(severity: QualityIssueSeverity): ReadinessRiskLevel { return ({ INFO: ReadinessRiskLevel.NONE, LOW: ReadinessRiskLevel.LOW, MEDIUM: ReadinessRiskLevel.MEDIUM, HIGH: ReadinessRiskLevel.HIGH, CRITICAL: ReadinessRiskLevel.CRITICAL })[severity]; }
  private fromPlagiarismRisk(risk: PlagiarismRiskLevel): ReadinessRiskLevel { return ({ NONE: ReadinessRiskLevel.NONE, LOW: ReadinessRiskLevel.LOW, MEDIUM: ReadinessRiskLevel.MEDIUM, HIGH: ReadinessRiskLevel.HIGH, CRITICAL: ReadinessRiskLevel.CRITICAL })[risk]; }
  private async validateTarget(dto: Pick<CreatePublicationReadinessDto, 'projectId' | 'targetType' | 'targetId' | 'manuscriptVersion'>): Promise<void> { const records = await this.contents.findByProjectId(dto.projectId); if (!records.length) throw new NotFoundException('Manuscript target not found'); const actualVersion = records.map((item) => item.contentVersion).join('+'); if (actualVersion !== dto.manuscriptVersion) throw new ConflictException('Manuscript version mismatch'); if (dto.targetType === ReadinessTargetType.MANUSCRIPT && dto.targetId !== dto.projectId && !records.some((item) => item.contentId === dto.targetId || String(item._id) === dto.targetId)) throw new BadRequestException('Target does not belong to the project'); }
  private async document(id: string): Promise<PublicationReadinessDocument> { const item = await this.repository.findById(id); if (!item) throw new NotFoundException('Publication readiness assessment not found'); return item; }
}
