import { randomUUID } from 'crypto';
import { Injectable } from '@nestjs/common';
import { ExternalVerificationBoundary, FactConsistency, FactConsistencyCategory, FactConsistencyScope, FactConsistencyStatus, FactConsistencyTargetType, FactIssueSeverity, FactPublicationRecommendation, FactRiskLevel } from './entities/fact-consistency.entity';
import type { FactAnalysisResult } from './interfaces/fact-consistency.interface';

@Injectable()
export class FactConsistencyFactory {
  create(input: { projectId: string; targetType: FactConsistencyTargetType; targetId: string; manuscriptVersion: string; scope: FactConsistencyScope; validationVersion: number; createdBy?: string }, result: FactAnalysisResult): Partial<FactConsistency> {
    const by = (categories: FactConsistencyCategory[]) => result.issues.filter((issue) => categories.includes(issue.category)); const score = (issues: typeof result.issues) => Math.max(0, 100 - issues.reduce((total, issue) => total + ({ INFO: 2, LOW: 5, MEDIUM: 10, HIGH: 20, CRITICAL: 35 }[issue.severity]), 0));
    const contradictions = by([FactConsistencyCategory.INTERNAL_CONTRADICTION, FactConsistencyCategory.CROSS_CHAPTER_CONTRADICTION, FactConsistencyCategory.DUPLICATE_CLAIM_CONFLICT, FactConsistencyCategory.CAUSE_EFFECT_CONFLICT]); const unsupportedClaims = by([FactConsistencyCategory.UNSUPPORTED_CLAIM, FactConsistencyCategory.UNVERIFIABLE_CLAIM_RISK]); const citationIssues = by([FactConsistencyCategory.CITATION_MISSING, FactConsistencyCategory.CITATION_MISMATCH]); const timelineIssues = by([FactConsistencyCategory.TIMELINE_INCONSISTENCY, FactConsistencyCategory.DATE_INCONSISTENCY]); const numericIssues = by([FactConsistencyCategory.NUMERIC_INCONSISTENCY, FactConsistencyCategory.STATISTICAL_INCONSISTENCY]); const entityIssues = by([FactConsistencyCategory.ENTITY_INCONSISTENCY, FactConsistencyCategory.NAME_INCONSISTENCY, FactConsistencyCategory.LOCATION_INCONSISTENCY]); const terminologyIssues = by([FactConsistencyCategory.TERMINOLOGY_INCONSISTENCY, FactConsistencyCategory.DEFINITION_INCONSISTENCY]);
    const internalConsistencyScore = score(contradictions); const claimSupportScore = score(unsupportedClaims); const citationCoverageScore = result.claims.length ? Math.round(result.claims.filter((claim) => claim.citations.length).length / result.claims.length * 100) : 100; const timelineConsistencyScore = score(timelineIssues); const numericConsistencyScore = score(numericIssues); const entityConsistencyScore = score([...entityIssues, ...terminologyIssues]); const overallScore = Math.round((internalConsistencyScore + claimSupportScore + citationCoverageScore + timelineConsistencyScore + numericConsistencyScore + entityConsistencyScore) / 6); const factRiskScore = 100 - overallScore; const critical = result.issues.some((issue) => issue.severity === FactIssueSeverity.CRITICAL); const riskLevel = critical ? FactRiskLevel.CRITICAL : factRiskScore >= 60 ? FactRiskLevel.HIGH : factRiskScore >= 35 ? FactRiskLevel.MEDIUM : factRiskScore > 0 ? FactRiskLevel.LOW : FactRiskLevel.NONE; const publicationRecommendation = critical ? FactPublicationRecommendation.BLOCK : riskLevel === FactRiskLevel.HIGH ? FactPublicationRecommendation.REVISE : riskLevel === FactRiskLevel.MEDIUM ? FactPublicationRecommendation.REVIEW : FactPublicationRecommendation.PUBLISH;
    return { validationId: `FCV-${randomUUID()}`, ...input, ...result, extractedClaims: result.claims, contradictions, unsupportedClaims, citationIssues, timelineIssues, numericIssues, entityIssues, terminologyIssues, recommendations: [...new Set(result.issues.map((issue) => issue.recommendation))], overallScore, internalConsistencyScore, claimSupportScore, citationCoverageScore, timelineConsistencyScore, numericConsistencyScore, entityConsistencyScore, factRiskScore, riskLevel, publicationRecommendation, externalVerificationBoundary: result.claims.length ? ExternalVerificationBoundary.EXTERNAL_VERIFICATION_PENDING : ExternalVerificationBoundary.EXTERNAL_VERIFICATION_NOT_REQUIRED, status: FactConsistencyStatus.COMPLETED, failureCode: null, failureMessage: null, requestMetadata: { externalSourceUsed: false, validationBoundary: ExternalVerificationBoundary.INTERNAL_CONSISTENCY_VALIDATION }, isDeleted: false, createdBy: input.createdBy ?? null, updatedBy: input.createdBy ?? null };
  }
}
