import { Activity, AlertTriangle, Archive, Bell, Briefcase, CheckCircle2, Cloud, Cog, Database, Flag, HardDrive, HeartPulse, KeyRound, Lock, RefreshCw, Server, Shield, Users, Workflow } from 'lucide-react';
import { DashboardKPI } from '@/features/analytics-dashboard/components/dashboard-kpi';
import { AnalyticsTable } from '@/features/analytics-dashboard/components/analytics-table';
import { DashboardPanel } from '@/features/analytics-dashboard/components/dashboard-layout';
import { WidgetEmptyState, WidgetPartialDataState } from '@/features/analytics-dashboard/components/dashboard-states';
import { formatDate, formatLabel, formatNumber, formatPercentage } from '@/features/analytics-dashboard/lib/formatters';
import type { DashboardFilters, KPIValue } from '@/features/analytics-dashboard/types';
import type { OperationalActivityItem, OperationalFreshnessItem, OperationalQueueItem, OperationalStatusItem } from '../types';
import { useAdministrationDashboard, useOperationsDashboard } from '../hooks/use-operations-admin-queries';

function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) {
  return <div className="mb-4 flex items-center gap-2 text-lg font-semibold">{icon}<h2>{title}</h2></div>;
}

function KPIGrid({ title, icon, items, empty }: { title: string; icon: React.ReactNode; items?: KPIValue[]; empty: string }) {
  if (!items?.length) return <DashboardPanel><WidgetEmptyState title={`${title} unavailable`} description={empty} /></DashboardPanel>;
  return <DashboardPanel><SectionTitle icon={icon} title={title} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <DashboardKPI key={item.label} value={item} />)}</div></DashboardPanel>;
}

function QueueTable({ title, icon, rows, empty }: { title: string; icon: React.ReactNode; rows?: OperationalQueueItem[]; empty: string }) {
  if (!rows?.length) return <DashboardPanel><WidgetEmptyState title={`${title} unavailable`} description={empty} /></DashboardPanel>;
  return <DashboardPanel><SectionTitle icon={icon} title={title} /><AnalyticsTable<OperationalQueueItem & Record<string, unknown>> rows={rows as unknown as Array<OperationalQueueItem & Record<string, unknown>>} columns={[{ key: 'title', header: 'Name' }, { key: 'status', header: 'Status', render: (value) => formatLabel(value as string) }, { key: 'count', header: 'Count', align: 'right', render: (value) => formatNumber(value as number) }, { key: 'progress', header: 'Progress', align: 'right', render: (value) => formatPercentage(value as number) }, { key: 'updatedAt', header: 'Updated', render: (value) => formatDate(value as string) }]} /></DashboardPanel>;
}

function StatusTable({ title, icon, rows, empty }: { title: string; icon: React.ReactNode; rows?: OperationalStatusItem[]; empty: string }) {
  if (!rows?.length) return <DashboardPanel><WidgetEmptyState title={`${title} unavailable`} description={empty} /></DashboardPanel>;
  return <DashboardPanel><SectionTitle icon={icon} title={title} /><AnalyticsTable<OperationalStatusItem & Record<string, unknown>> rows={rows as unknown as Array<OperationalStatusItem & Record<string, unknown>>} columns={[{ key: 'label', header: 'Name' }, { key: 'status', header: 'Status', render: (value) => formatLabel(value as string) }, { key: 'message', header: 'Message' }, { key: 'updatedAt', header: 'Updated', render: (value) => formatDate(value as string) }]} /></DashboardPanel>;
}

function ActivityTable({ title, icon, rows, empty }: { title: string; icon: React.ReactNode; rows?: OperationalActivityItem[]; empty: string }) {
  if (!rows?.length) return <DashboardPanel><WidgetEmptyState title={`${title} unavailable`} description={empty} /></DashboardPanel>;
  return <DashboardPanel><SectionTitle icon={icon} title={title} /><AnalyticsTable<OperationalActivityItem & Record<string, unknown>> rows={rows as unknown as Array<OperationalActivityItem & Record<string, unknown>>} columns={[{ key: 'title', header: 'Event' }, { key: 'type', header: 'Type', render: (value) => formatLabel(value as string) }, { key: 'severity', header: 'Severity', render: (value) => formatLabel(value as string) }, { key: 'status', header: 'Status', render: (value) => formatLabel(value as string) }, { key: 'timestamp', header: 'Time', render: (value) => formatDate(value as string) }]} /></DashboardPanel>;
}

function FreshnessTable({ title, rows }: { title: string; rows?: OperationalFreshnessItem[] }) {
  if (!rows?.length) return <DashboardPanel><WidgetEmptyState title={`${title} unavailable`} description="Freshness metadata will appear here." /></DashboardPanel>;
  return <DashboardPanel><SectionTitle icon={<RefreshCw className="h-5 w-5 text-primary" />} title={title} /><AnalyticsTable<OperationalFreshnessItem & Record<string, unknown>> rows={rows as unknown as Array<OperationalFreshnessItem & Record<string, unknown>>} columns={[{ key: 'label', header: 'Source' }, { key: 'status', header: 'Status', render: (value) => formatLabel(value as string) }, { key: 'timestamp', header: 'Updated', render: (value) => formatDate(value as string) }]} /></DashboardPanel>;
}

export function SystemOverview({ filters }: { filters: DashboardFilters }) { const data = useOperationsDashboard(filters).data; return <><WidgetPartialDataState completeness={data.metadata?.completeness} /><KPIGrid title="System Overview" icon={<HeartPulse className="h-5 w-5 text-primary" />} items={data.systemOverview} empty="System overview metrics will appear here." /></>; }
export function PublishingQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Publishing Queue" icon={<Workflow className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.publishingQueue} empty="Publishing workflow queue will appear here." />; }
export function ImportQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Import Queue" icon={<Database className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.importQueue} empty="Import queue status will appear here." />; }
export function SynchronizationQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Synchronization Queue" icon={<RefreshCw className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.synchronizationQueue} empty="Sync queue status will appear here." />; }
export function AnalyticsQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Analytics Queue" icon={<Activity className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.analyticsQueue} empty="Analytics queue status will appear here." />; }
export function OpportunityOperationsQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Opportunity Queue" icon={<CheckCircle2 className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.opportunityQueue} empty="Opportunity queue status will appear here." />; }
export function AIInsightOperationsQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="AI Insight Queue" icon={<Cloud className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.aiInsightQueue} empty="AI insight queue status will appear here." />; }
export function BackgroundJobs({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Background Jobs" icon={<Cog className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.backgroundJobs} empty="Background jobs will appear here." />; }
export function FailedJobs({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Failed Jobs" icon={<AlertTriangle className="h-5 w-5 text-destructive" />} rows={useOperationsDashboard(filters).data.failedJobs} empty="Failed jobs will appear here." />; }
export function RetryQueue({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Retry Queue" icon={<RefreshCw className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.retryQueue} empty="Retry queue will appear here." />; }
export function ActiveWorkers({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Active Workers" icon={<Server className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.activeWorkers} empty="Active worker status will appear here." />; }
export function ProviderStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Provider Status" icon={<Cloud className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.providerStatus} empty="Provider operational status will appear here." />; }
export function MarketplaceStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Marketplace Status" icon={<Briefcase className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.marketplaceStatus} empty="Marketplace operational status will appear here." />; }
export function APIHealth({ filters }: { filters: DashboardFilters }) { return <StatusTable title="API Health" icon={<HeartPulse className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.apiHealth} empty="API health status will appear here." />; }
export function StorageStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Storage Status" icon={<HardDrive className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.storageStatus} empty="Storage status will appear here." />; }
export function ProcessingStatistics({ filters }: { filters: DashboardFilters }) { return <KPIGrid title="Processing Statistics" icon={<Activity className="h-5 w-5 text-primary" />} items={useOperationsDashboard(filters).data.processingStatistics} empty="Processing statistics will appear here." />; }
export function ErrorSummary({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Error Summary" icon={<AlertTriangle className="h-5 w-5 text-destructive" />} rows={useOperationsDashboard(filters).data.errorSummary} empty="Error summaries will appear here." />; }
export function OperationalAlerts({ filters }: { filters: DashboardFilters }) { return <ActivityTable title="Operational Alerts" icon={<Bell className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.operationalAlerts} empty="Operational alerts will appear here." />; }
export function RecentOperations({ filters }: { filters: DashboardFilters }) { return <ActivityTable title="Recent Operations" icon={<Activity className="h-5 w-5 text-primary" />} rows={useOperationsDashboard(filters).data.recentOperations} empty="Recent operations will appear here." />; }
export function OperationsDataFreshness({ filters }: { filters: DashboardFilters }) { return <FreshnessTable title="Data Freshness" rows={useOperationsDashboard(filters).data.dataFreshness} />; }

export function UserSummaryAdmin({ filters }: { filters: DashboardFilters }) { return <KPIGrid title="User Summary" icon={<Users className="h-5 w-5 text-primary" />} items={useAdministrationDashboard(filters).data.userSummary} empty="User administration summary will appear here." />; }
export function RolesPermissionsSummary({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Roles & Permissions Summary" icon={<Shield className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.rolesPermissionsSummary} empty="Role and permission summary will appear here." />; }
export function WorkspaceSummary({ filters }: { filters: DashboardFilters }) { return <KPIGrid title="Workspace Summary" icon={<Briefcase className="h-5 w-5 text-primary" />} items={useAdministrationDashboard(filters).data.workspaceSummary} empty="Workspace summary will appear here." />; }
export function APIKeyStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="API Key Status" icon={<KeyRound className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.apiKeyStatus} empty="API key status will appear here without exposing secrets." />; }
export function ProviderConnections({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Provider Connections" icon={<Cloud className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.providerConnections} empty="Provider connection status will appear here." />; }
export function MarketplaceConnections({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Marketplace Connections" icon={<Briefcase className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.marketplaceConnections} empty="Marketplace connection status will appear here." />; }
export function ConfigurationStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Configuration Status" icon={<Cog className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.configurationStatus} empty="Sanitized configuration status will appear here." />; }
export function FeatureFlags({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Feature Flags" icon={<Flag className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.featureFlags} empty="Feature flag status will appear here." />; }
export function AuditSummary({ filters }: { filters: DashboardFilters }) { return <KPIGrid title="Audit Summary" icon={<Archive className="h-5 w-5 text-primary" />} items={useAdministrationDashboard(filters).data.auditSummary} empty="Audit summary will appear here." />; }
export function SecurityEvents({ filters }: { filters: DashboardFilters }) { return <ActivityTable title="Security Events" icon={<Lock className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.securityEvents} empty="Authorized security events will appear here." />; }
export function LoginActivity({ filters }: { filters: DashboardFilters }) { return <ActivityTable title="Login Activity" icon={<Users className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.loginActivity} empty="Login activity will appear here." />; }
export function SystemNotifications({ filters }: { filters: DashboardFilters }) { return <ActivityTable title="System Notifications" icon={<Bell className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.systemNotifications} empty="System notifications will appear here." />; }
export function ScheduledJobs({ filters }: { filters: DashboardFilters }) { return <QueueTable title="Scheduled Jobs" icon={<Cog className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.scheduledJobs} empty="Scheduled jobs will appear here." />; }
export function BackupStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Backup Status" icon={<HardDrive className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.backupStatus} empty="Backup status will appear here." />; }
export function MaintenanceStatus({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Maintenance Status" icon={<Cog className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.maintenanceStatus} empty="Maintenance status will appear here." />; }
export function ApplicationVersion({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Application Version" icon={<Server className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.applicationVersion} empty="Application version will appear here." />; }
export function EnvironmentInformation({ filters }: { filters: DashboardFilters }) { return <StatusTable title="Environment Information" icon={<Database className="h-5 w-5 text-primary" />} rows={useAdministrationDashboard(filters).data.environmentInformation} empty="Sanitized environment information will appear here." />; }
