import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { BookMetadataRepository } from '../book-metadata/book-metadata.repository';
import { ExportRepository } from '../export/export.repository';
import { PublishingTargetExecutionRepository } from '../publishing-workflow/publishing-target-execution.repository';
import type { AmazonKdpQueryDto, PrepareAmazonKdpPackageDto, RecordAmazonKdpSubmissionDto, UpdateAmazonKdpChecklistItemDto, UpdateAmazonKdpStatusDto } from './dto';
import { AmazonKdpChecklistStatus, AmazonKdpPackage, AmazonKdpPackageDocument, AmazonKdpProviderKey, AmazonKdpStatus } from './entities/amazon-kdp.entity';
import { AmazonKdpPackageBuilder } from './amazon-kdp-package.builder';
import { AmazonKdpRepository } from './amazon-kdp.repository';
import { AmazonKdpStatusMapper } from './amazon-kdp-status.mapper';
import { AmazonKdpValidator } from './amazon-kdp.validator';
import { amazonKdpDefaultConfiguration } from './config/amazon-kdp.config';

@Injectable()
export class AmazonKdpManualSubmissionService {
  constructor(private readonly metadata: BookMetadataRepository, private readonly exports: ExportRepository, private readonly targets: PublishingTargetExecutionRepository, private readonly repository: AmazonKdpRepository, private readonly builder: AmazonKdpPackageBuilder, private readonly statusMapper: AmazonKdpStatusMapper, private readonly validator: AmazonKdpValidator) {}
  async prepare(dto: PrepareAmazonKdpPackageDto) {
    const metadata = (await this.metadata.findByProjectId(dto.projectId))[0]; if (!metadata) throw new NotFoundException('Book metadata is required for KDP package preparation');
    const exportJob = await this.exports.latestExport(dto.projectId);
    const prepared = this.builder.build({ projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, kdpFormat: dto.kdpFormat, metadata: metadata.toObject() as unknown as Record<string, unknown>, exportJob });
    const active = await this.repository.findActivePackage(dto.targetExecutionId, prepared.submissionFingerprint); if (active) return active;
    const latest = await this.repository.findLatestPackage(dto.targetExecutionId);
    return this.repository.create({ packageId: `KDP-${Date.now()}`, workflowId: dto.workflowId, targetExecutionId: dto.targetExecutionId, projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, providerKey: AmazonKdpProviderKey.AMAZON_KDP, integrationMode: amazonKdpDefaultConfiguration.integrationMode, kdpFormat: dto.kdpFormat, primaryMarketplace: amazonKdpDefaultConfiguration.primaryMarketplace, metadataSnapshot: prepared.metadataSnapshot as unknown as Record<string, unknown>, rightsSnapshot: prepared.rightsSnapshot, pricingSnapshot: prepared.pricingSnapshot, printOptionsSnapshot: prepared.printOptionsSnapshot, artifactReferences: prepared.artifactReferences, coverReferences: prepared.coverReferences, submissionFingerprint: prepared.submissionFingerprint, packageVersion: (latest?.packageVersion ?? 0) + 1, checklistVersion: amazonKdpDefaultConfiguration.manualSubmissionChecklistVersion, checklist: prepared.checklist, checklistStatus: AmazonKdpChecklistStatus.NOT_STARTED, status: prepared.validationIssues.length ? AmazonKdpStatus.BLOCKED : AmazonKdpStatus.READY_FOR_SUBMISSION, externalTitleId: null, asin: null, isbn: prepared.metadataSnapshot.isbn ?? null, externalStatus: null, externalStatusMessage: null, readyForManualSubmissionAt: prepared.validationIssues.length ? null : new Date(), submittedAt: null, publishedAt: null, rejectedAt: null, actionRequiredAt: null, submittedBy: null, lastStatusUpdatedBy: null, sourceResultIds: { metadataId: String(metadata._id), exportJobId: exportJob ? String(exportJob._id) : '' }, validationIssues: prepared.validationIssues, warnings: prepared.warnings, statusHistory: [{ status: prepared.validationIssues.length ? AmazonKdpStatus.BLOCKED : AmazonKdpStatus.READY_FOR_SUBMISSION, statusMessage: 'KDP manual-assisted package prepared. External submission has not occurred.', recordedAt: new Date(), recordedBy: dto.createdBy ?? null }], isDeleted: false, deletedAt: null, deletedBy: null, createdBy: dto.createdBy ?? null, updatedBy: dto.createdBy ?? null });
  }
  async findById(id: string) { return this.document(id); }
  async latest(targetExecutionId: string) { const item = await this.repository.findLatestPackage(targetExecutionId); if (!item) throw new NotFoundException('KDP package not found'); return item; }
  async checklist(id: string) { return (await this.document(id)).checklist; }
  async updateChecklistItem(id: string, dto: UpdateAmazonKdpChecklistItemDto) { const item = await this.document(id); const checklist = item.checklist.map((check) => check.sequence === dto.sequence ? { ...check, completionStatus: dto.completionStatus } : check); const done = checklist.filter((check) => check.completionStatus === AmazonKdpChecklistStatus.COMPLETED).length; const checklistStatus = done === 0 ? AmazonKdpChecklistStatus.NOT_STARTED : done === checklist.length ? AmazonKdpChecklistStatus.COMPLETED : AmazonKdpChecklistStatus.IN_PROGRESS; return this.repository.update(id, { checklist, checklistStatus }); }
  async recordSubmission(id: string, dto: RecordAmazonKdpSubmissionDto, userId?: string) { const item = await this.document(id); if (item.status !== AmazonKdpStatus.READY_FOR_SUBMISSION) throw new ConflictException('KDP package is not ready for manual submission recording'); if (item.submittedAt) throw new ConflictException('KDP manual submission is already recorded'); const updated = await this.repository.update(id, { status: AmazonKdpStatus.SUBMISSION_RECORDED, externalTitleId: this.clean(dto.externalTitleId), asin: this.clean(dto.asin), isbn: this.clean(dto.isbn) ?? item.isbn, externalStatus: AmazonKdpStatus.SUBMISSION_RECORDED, externalStatusMessage: this.clean(dto.statusMessage) ?? 'Manual KDP submission recorded', submittedAt: new Date(), submittedBy: userId ?? dto.submittedBy ?? null, lastStatusUpdatedBy: userId ?? null, $push: { statusHistory: { status: AmazonKdpStatus.SUBMISSION_RECORDED, statusMessage: 'Manual KDP submission recorded', recordedAt: new Date(), recordedBy: userId ?? null } } }); await this.syncTarget(updated!); return updated; }
  async updateStatus(id: string, dto: UpdateAmazonKdpStatusDto, userId?: string) { const item = await this.document(id); this.validator.validateStatusTransition(item.status, dto.status); const dates: Partial<AmazonKdpPackage> = {}; if (dto.status === AmazonKdpStatus.LIVE) dates.publishedAt = new Date(); if (dto.status === AmazonKdpStatus.REJECTED) dates.rejectedAt = new Date(); if (dto.status === AmazonKdpStatus.ACTION_REQUIRED) dates.actionRequiredAt = new Date(); const updated = await this.repository.update(id, { ...dates, status: dto.status, externalStatus: dto.status, externalStatusMessage: this.clean(dto.statusMessage) ?? null, lastStatusUpdatedBy: userId ?? dto.recordedBy ?? null, $push: { statusHistory: { status: dto.status, statusMessage: this.clean(dto.statusMessage) ?? dto.status, recordedAt: new Date(), recordedBy: userId ?? dto.recordedBy ?? null } } }); await this.syncTarget(updated!); return updated; }
  async history(id: string) { return (await this.document(id)).statusHistory; }
  async search(query: AmazonKdpQueryDto) { const filter: FilterQuery<AmazonKdpPackage> = {}; if (query.projectId) filter.projectId = query.projectId; if (query.targetExecutionId) filter.targetExecutionId = query.targetExecutionId; if (query.status) filter.status = query.status; return this.repository.paginate(filter, query.page, query.limit); }
  async softDelete(id: string, userId?: string) { if (!(await this.repository.softDelete(id, userId))) throw new NotFoundException('KDP package not found'); }
  async restore(id: string) { const item = await this.repository.restore(id); if (!item) throw new NotFoundException('Deleted KDP package not found'); return item; }
  private async syncTarget(item: AmazonKdpPackageDocument): Promise<void> { const target = await this.targets.findById(item.targetExecutionId); if (target) await this.targets.update(String(target._id), { status: this.statusMapper.toTargetStatus(item.status), externalSubmissionId: item.externalTitleId ?? target.externalSubmissionId, externalPublicationId: item.asin ?? target.externalPublicationId, providerStatus: item.status, providerStatusMessage: item.externalStatusMessage }); }
  private async document(id: string): Promise<AmazonKdpPackageDocument> { const item = await this.repository.findById(id); if (!item) throw new NotFoundException('KDP package not found'); return item; }
  private clean(value?: string): string | null { if (!value) return null; return value.replace(/[<>"'`]/g, '').trim() || null; }
}
