import { BadRequestException, ConflictException, Injectable } from '@nestjs/common';
import { PublishingTargetStatus, PublishingWorkflowStatus } from './entities/publishing-workflow.entity';

@Injectable()
export class PublishingWorkflowValidator {
  validateWorkflowTransition(current: PublishingWorkflowStatus, next: PublishingWorkflowStatus): void { const allowed: Record<PublishingWorkflowStatus, PublishingWorkflowStatus[]> = { DRAFT: [PublishingWorkflowStatus.PENDING_VALIDATION, PublishingWorkflowStatus.BLOCKED, PublishingWorkflowStatus.SUPERSEDED], PENDING_VALIDATION: [PublishingWorkflowStatus.VALIDATING, PublishingWorkflowStatus.CANCELLED], VALIDATING: [PublishingWorkflowStatus.READY, PublishingWorkflowStatus.BLOCKED, PublishingWorkflowStatus.FAILED], READY: [PublishingWorkflowStatus.QUEUED, PublishingWorkflowStatus.CANCELLED], QUEUED: [PublishingWorkflowStatus.PROCESSING, PublishingWorkflowStatus.CANCEL_REQUESTED, PublishingWorkflowStatus.CANCELLED], PROCESSING: [PublishingWorkflowStatus.PARTIALLY_COMPLETED, PublishingWorkflowStatus.COMPLETED, PublishingWorkflowStatus.RETRY_PENDING, PublishingWorkflowStatus.FAILED, PublishingWorkflowStatus.CANCEL_REQUESTED], PARTIALLY_COMPLETED: [PublishingWorkflowStatus.COMPLETED, PublishingWorkflowStatus.FAILED, PublishingWorkflowStatus.RETRY_PENDING], COMPLETED: [PublishingWorkflowStatus.SUPERSEDED], RETRY_PENDING: [PublishingWorkflowStatus.PROCESSING, PublishingWorkflowStatus.CANCELLED], FAILED: [PublishingWorkflowStatus.PROCESSING, PublishingWorkflowStatus.SUPERSEDED], CANCEL_REQUESTED: [PublishingWorkflowStatus.CANCELLED], CANCELLED: [], BLOCKED: [PublishingWorkflowStatus.PENDING_VALIDATION, PublishingWorkflowStatus.SUPERSEDED], SUPERSEDED: [] }; if (!allowed[current].includes(next)) throw new BadRequestException(`Invalid publishing workflow status transition from ${current} to ${next}`); }
  validateTargetTransition(current: PublishingTargetStatus, next: PublishingTargetStatus): void { const terminal = [PublishingTargetStatus.PUBLISHED, PublishingTargetStatus.REJECTED, PublishingTargetStatus.CANCELLED, PublishingTargetStatus.SKIPPED]; if (terminal.includes(current) && current !== next) throw new BadRequestException(`Invalid publishing target status transition from ${current} to ${next}`); }
  validateReady(input: { readinessDecision?: string; readinessStatus?: string; manualApprovalRequired?: boolean; manualApprovalStatus?: string; blockers?: string[] }): void { if (!input.readinessDecision || !['READY', 'READY_WITH_WARNINGS'].includes(input.readinessDecision)) throw new ConflictException('Publication readiness does not allow publishing'); if (input.readinessStatus !== 'APPROVED' && input.manualApprovalRequired) throw new ConflictException('Manual publication readiness approval is required'); if (input.manualApprovalRequired && input.manualApprovalStatus !== 'APPROVED') throw new ConflictException('Manual approval is not complete'); if ((input.blockers ?? []).length) throw new ConflictException('Critical publication blockers remain'); }
}
