import { createHash, randomUUID } from 'crypto';
import { Injectable } from '@nestjs/common';
import type { PublishingWorkflowPolicy, PublishingTargetConfig } from './config/publishing-workflow.config';
import { PublishingStepStatus, PublishingStepType, PublishingTargetStatus, PublishingWorkflow, PublishingWorkflowEventType, PublishingWorkflowStatus } from './entities/publishing-workflow.entity';
import type { PublishingTargetExecution } from './entities/publishing-target-execution.entity';
import type { PublishingWorkflowStep } from './entities/publishing-workflow-step.entity';
import type { PublishingWorkflowEvent } from './entities/publishing-workflow-event.entity';

@Injectable()
export class PublishingWorkflowFactory {
  fingerprint(input: { projectId: string; manuscriptVersion: string; publicationScope: string; targets: Pick<PublishingTargetConfig, 'targetKey' | 'providerKey'>[]; policyVersion: string }): string { return createHash('sha256').update(JSON.stringify({ ...input, targets: input.targets.map((target) => `${target.providerKey}:${target.targetKey}`).sort() })).digest('hex'); }
  idempotencyKey(input: { projectId: string; manuscriptVersion: string; publicationScope: string; fingerprint: string }): string { return createHash('sha256').update(`${input.projectId}:${input.manuscriptVersion}:${input.publicationScope}:${input.fingerprint}`).digest('hex'); }
  workflow(input: Partial<PublishingWorkflow> & { projectId: string; manuscriptVersion: string; publicationScope: PublishingWorkflow['publicationScope']; requestedBy: string }, policy: PublishingWorkflowPolicy, fingerprint: string, idempotencyKey: string): Partial<PublishingWorkflow> { return { workflowId: `PW-${randomUUID()}`, policyProfile: policy.profile, policyVersion: policy.policyVersion, idempotencyKey, submissionFingerprint: fingerprint, status: PublishingWorkflowStatus.DRAFT, targetIds: [], sourceResultIds: {}, sourceResultVersions: {}, exportArtifactIds: [], metadataId: null, tocId: null, coverAssetIds: [], scheduledAt: null, queuedAt: null, startedAt: null, completedAt: null, failedAt: null, cancelledAt: null, cancellationReason: null, blockedReasons: [], currentStep: null, retryCount: 0, maximumRetries: policy.maximumRetryCount, nextRetryAt: null, lastError: null, isDeleted: false, createdBy: input.requestedBy, updatedBy: input.requestedBy, ...input }; }
  target(workflow: PublishingWorkflow & { _id: unknown }, target: PublishingTargetConfig): Partial<PublishingTargetExecution> { const fingerprint = this.fingerprint({ projectId: workflow.projectId, manuscriptVersion: workflow.manuscriptVersion, publicationScope: workflow.publicationScope, targets: [target], policyVersion: workflow.policyVersion }); return { targetExecutionId: `PWT-${randomUUID()}`, workflowId: String(workflow._id), projectId: workflow.projectId, targetType: target.targetType, targetKey: target.targetKey, providerKey: target.providerKey, configurationProfile: target.configurationProfile, status: PublishingTargetStatus.PENDING, capabilities: target.capabilities, requestedFormats: target.requestedFormats, packageReference: null, packageChecksum: null, submissionFingerprint: fingerprint, idempotencyKey: this.idempotencyKey({ projectId: workflow.projectId, manuscriptVersion: workflow.manuscriptVersion, publicationScope: workflow.publicationScope, fingerprint }), externalSubmissionId: null, externalPublicationId: null, normalizedResponse: {}, providerStatus: null, providerStatusMessage: null, retryCount: 0, maximumRetries: workflow.maximumRetries, nextRetryAt: null, submittedAt: null, publishedAt: null, rejectedAt: null, failedAt: null, cancelledAt: null, error: null }; }
  steps(workflowId: string): Partial<PublishingWorkflowStep>[] { return [PublishingStepType.LOAD_PROJECT, PublishingStepType.VALIDATE_READINESS, PublishingStepType.VALIDATE_METADATA, PublishingStepType.VALIDATE_EXPORTS, PublishingStepType.RESOLVE_TARGETS, PublishingStepType.PREPARE_PACKAGE, PublishingStepType.QUEUE_SUBMISSION, PublishingStepType.SUBMIT, PublishingStepType.POLL_STATUS, PublishingStepType.PROCESS_RESPONSE, PublishingStepType.COMPLETE].map((stepType, index) => ({ stepId: `PWS-${randomUUID()}`, workflowId, targetExecutionId: null, stepType, sequence: index + 1, status: PublishingStepStatus.PENDING, attempt: 1, startedAt: null, completedAt: null, duration: 0, inputReferences: {}, outputReferences: {}, error: null, retryable: false, nextRetryAt: null })); }
  event(workflowId: string, eventType: PublishingWorkflowEventType, message: string, createdBy?: string, targetExecutionId?: string, metadata: Record<string, unknown> = {}): Partial<PublishingWorkflowEvent> { return { eventId: `PWE-${randomUUID()}`, workflowId, targetExecutionId: targetExecutionId ?? null, eventType, message, metadata, createdBy: createdBy ?? null }; }
}
