import { PieChart } from 'lucide-react';
import type { DashboardDefinition, DashboardWidgetDefinition } from '@/features/analytics-dashboard/types';
import { platformDefaults } from '@/features/platform-registry';
import {
  ExecutiveAIInsightsSection,
  ExecutiveAlertsSection,
  ExecutiveDashboardSummary,
  ExecutiveFormatOverviewSection,
  ExecutiveFreshnessSection,
  ExecutiveGeographicOverviewSection,
  ExecutiveKPISection,
  ExecutiveMarketplaceOverviewSection,
  ExecutiveOperationalWarningsSection,
  ExecutiveOpportunitySection,
  ExecutivePerformanceTrendSection,
  ExecutivePortfolioHealthSection,
  ExecutiveProviderOverviewSection,
  ExecutiveRiskSection,
  ExecutiveTopBooksSection,
  ExecutiveUnderperformingBooksSection,
  ExecutiveActivitySection,
} from './components/executive-sections';

export const executiveDashboardWidgets: DashboardWidgetDefinition[] = [
  { key: 'EXECUTIVE_AI_SUMMARY', type: 'INSIGHT', title: 'AI Executive Summary', category: 'AI_INSIGHTS', requiredPermissions: ['analytics:read', 'ai-insights:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-ai-summary' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'MANUAL', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveDashboardSummary filters={filters} /> },
  { key: 'EXECUTIVE_KPIS', type: 'KPI', title: 'Executive KPI Row', category: 'FINANCIAL', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-kpis' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 12, rows: 1 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveKPISection filters={filters} /> },
  { key: 'EXECUTIVE_PORTFOLIO_HEALTH', type: 'HEALTH', title: 'Portfolio Health', category: 'OVERVIEW', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-portfolio-health' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutivePortfolioHealthSection filters={filters} /> },
  { key: 'EXECUTIVE_PERFORMANCE_TREND', type: 'TREND_CHART', title: 'Performance Trend', category: 'PERFORMANCE', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-performance-trend' }, defaultSize: { columns: 12, rows: 3 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV', 'PNG'], version: 1, render: ({ filters }) => <ExecutivePerformanceTrendSection filters={filters} /> },
  { key: 'EXECUTIVE_TOP_BOOKS', type: 'RANKING', title: 'Top Books', category: 'PERFORMANCE', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-top-books' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveTopBooksSection filters={filters} /> },
  { key: 'EXECUTIVE_UNDERPERFORMING_BOOKS', type: 'RANKING', title: 'Books Needing Attention', category: 'OPPORTUNITIES', requiredPermissions: ['analytics:read', 'opportunities:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-underperforming-books' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveUnderperformingBooksSection filters={filters} /> },
  { key: 'EXECUTIVE_PROVIDER_CONTRIBUTION', type: 'BREAKDOWN', title: 'Provider Overview', category: 'DISTRIBUTION', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-provider-contribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveProviderOverviewSection filters={filters} /> },
  { key: 'EXECUTIVE_MARKETPLACE_CONTRIBUTION', type: 'BREAKDOWN', title: 'Marketplace Overview', category: 'DISTRIBUTION', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-marketplace-contribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveMarketplaceOverviewSection filters={filters} /> },
  { key: 'EXECUTIVE_GEOGRAPHIC_PERFORMANCE', type: 'BAR_CHART', title: 'Geographic Overview', category: 'DISTRIBUTION', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-geographic-performance' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveGeographicOverviewSection filters={filters} /> },
  { key: 'EXECUTIVE_FORMAT_PERFORMANCE', type: 'BAR_CHART', title: 'Format Overview', category: 'DISTRIBUTION', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-format-performance' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveFormatOverviewSection filters={filters} /> },
  { key: 'EXECUTIVE_TOP_OPPORTUNITIES', type: 'OPPORTUNITY', title: 'Priority Opportunities', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-top-opportunities' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'MANUAL', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveOpportunitySection filters={filters} /> },
  { key: 'EXECUTIVE_AI_INSIGHTS', type: 'INSIGHT', title: 'AI Insights', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-ai-insights' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'MANUAL', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveAIInsightsSection filters={filters} /> },
  { key: 'EXECUTIVE_RISKS', type: 'ALERT', title: 'Business Risks', category: 'OPERATIONS', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-risks' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveRiskSection filters={filters} /> },
  { key: 'EXECUTIVE_ALERTS', type: 'ALERT', title: 'Executive Alerts', category: 'OPERATIONS', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-alerts' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveAlertsSection filters={filters} /> },
  { key: 'EXECUTIVE_RECENT_ACTIVITY', type: 'ACTIVITY', title: 'Recent Activity', category: 'OPERATIONS', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-recent-activity' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveActivitySection filters={filters} /> },
  { key: 'EXECUTIVE_DATA_FRESHNESS', type: 'HEALTH', title: 'Data Freshness', category: 'OPERATIONS', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-data-freshness' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveFreshnessSection filters={filters} /> },
  { key: 'EXECUTIVE_OPERATIONAL_WARNINGS', type: 'ALERT', title: 'Operational Warnings', category: 'OPERATIONS', requiredPermissions: ['analytics:read'], supportedDashboards: ['executive-overview'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'executive-operational-warnings' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExecutiveOperationalWarningsSection filters={filters} /> },
];

export const executiveDashboardDefinition: DashboardDefinition = {
  key: 'executive-overview',
  route: '/analytics/executive',
  title: 'Executive Dashboard',
  description: 'A concise decision surface for portfolio performance, financial health, risks, opportunities, and AI-generated executive insights.',
  icon: PieChart,
  category: 'OVERVIEW',
  order: 20,
  enabled: true,
  featureFlag: 'executiveDashboard',
  requiredPermissions: ['analytics:read'],
  supportedScopes: ['PORTFOLIO', 'PROJECT'],
  defaultScope: 'PORTFOLIO',
  supportedFilters: ['projectId', 'portfolioId', 'period', 'dateRange', 'comparisonMode', 'comparisonDateRange', 'currencyCode', 'providerKeys', 'marketplaceIds', 'countryCodes', 'territoryCodes', 'formats', 'authorIds', 'seriesIds'],
  defaultFilters: { scope: 'PORTFOLIO', period: 'LAST_30_DAYS', comparisonMode: 'PREVIOUS_PERIOD', currencyCode: platformDefaults.reportingCurrency },
  supportedPeriods: ['LAST_7_DAYS', 'LAST_30_DAYS', 'LAST_90_DAYS', 'CURRENT_MONTH', 'PREVIOUS_MONTH', 'CURRENT_QUARTER', 'CURRENT_YEAR', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD', 'PREVIOUS_CALENDAR_PERIOD', 'PREVIOUS_YEAR', 'CUSTOM'],
  defaultComparisonMode: 'PREVIOUS_PERIOD',
  supportedCurrencies: platformDefaults.supportedCurrencies,
  widgetDefinitions: executiveDashboardWidgets,
  layoutDefinition: {
    columns: 12,
    density: 'COMFORTABLE',
    minWidgetHeight: 180,
    items: [
      { widgetKey: 'EXECUTIVE_AI_SUMMARY', colSpan: 12, order: 1 },
      { widgetKey: 'EXECUTIVE_KPIS', colSpan: 12, order: 2 },
      { widgetKey: 'EXECUTIVE_PORTFOLIO_HEALTH', colSpan: 12, order: 3 },
      { widgetKey: 'EXECUTIVE_PERFORMANCE_TREND', colSpan: 12, order: 4 },
      { widgetKey: 'EXECUTIVE_TOP_BOOKS', colSpan: 6, order: 5 },
      { widgetKey: 'EXECUTIVE_UNDERPERFORMING_BOOKS', colSpan: 6, order: 6 },
      { widgetKey: 'EXECUTIVE_PROVIDER_CONTRIBUTION', colSpan: 6, order: 7 },
      { widgetKey: 'EXECUTIVE_MARKETPLACE_CONTRIBUTION', colSpan: 6, order: 8 },
      { widgetKey: 'EXECUTIVE_GEOGRAPHIC_PERFORMANCE', colSpan: 6, order: 9 },
      { widgetKey: 'EXECUTIVE_FORMAT_PERFORMANCE', colSpan: 6, order: 10 },
      { widgetKey: 'EXECUTIVE_TOP_OPPORTUNITIES', colSpan: 6, order: 11 },
      { widgetKey: 'EXECUTIVE_AI_INSIGHTS', colSpan: 6, order: 12 },
      { widgetKey: 'EXECUTIVE_RISKS', colSpan: 6, order: 13 },
      { widgetKey: 'EXECUTIVE_ALERTS', colSpan: 6, order: 14 },
      { widgetKey: 'EXECUTIVE_RECENT_ACTIVITY', colSpan: 6, order: 15 },
      { widgetKey: 'EXECUTIVE_DATA_FRESHNESS', colSpan: 6, order: 16 },
      { widgetKey: 'EXECUTIVE_OPERATIONAL_WARNINGS', colSpan: 12, order: 17 },
    ],
  },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
  metadata: { domain: 'executive', defaultRankingSize: 5, estimatedValuesRequireBackendFlag: true },
};
