import { AnalyticsPeriod } from '../entities/book-analytics.entity';

export interface AnalyticsMetricDefinition { metricKey: string; displayName: string; description: string; category: string; supportedScopes: string[]; supportedDimensions: string[]; requiredDataSources: string[]; aggregationType: 'SUM' | 'AVG' | 'COUNT' | 'DERIVED'; valueType: 'NUMBER' | 'MONEY' | 'PERCENTAGE' | 'DATE' | 'STRING'; currencyAware: boolean; percentage: boolean; precision: number; unit: string | null; enabled: boolean; version: string }
export interface BookAnalyticsPolicy { policyVersion: string; enabledMetrics: string[]; enabledDimensions: string[]; defaultReportingCurrency: string; defaultTimezone: string; defaultAnalyticsPeriod: AnalyticsPeriod; weekStartDay: number; cacheTtlSeconds: number; batchSize: number; workerConcurrency: number; maximumRetries: number; metricPrecision: number; includeEstimatedRoyalties: boolean; preferFinalizedRoyalties: boolean; snapshotRetentionDays: number }
export const coreAnalyticsMetrics: AnalyticsMetricDefinition[] = [
  { metricKey: 'unitsSold', displayName: 'Units Sold', description: 'Total units sold', category: 'SALES', supportedScopes: ['BOOK', 'EDITION', 'FORMAT', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'PROJECT', 'PORTFOLIO'], supportedDimensions: ['bookId', 'editionId', 'format', 'providerKey', 'marketplaceId', 'countryCode'], requiredDataSources: ['canonical_sales'], aggregationType: 'SUM', valueType: 'NUMBER', currencyAware: false, percentage: false, precision: 0, unit: 'units', enabled: true, version: '1' },
  { metricKey: 'grossSales', displayName: 'Gross Sales', description: 'Gross sales amount', category: 'SALES', supportedScopes: ['BOOK', 'PROJECT', 'PORTFOLIO'], supportedDimensions: ['currencyCode'], requiredDataSources: ['canonical_sales'], aggregationType: 'SUM', valueType: 'MONEY', currencyAware: true, percentage: false, precision: 2, unit: null, enabled: true, version: '1' },
  { metricKey: 'netSales', displayName: 'Net Sales', description: 'Net sales amount', category: 'SALES', supportedScopes: ['BOOK', 'PROJECT', 'PORTFOLIO'], supportedDimensions: ['currencyCode'], requiredDataSources: ['canonical_sales'], aggregationType: 'SUM', valueType: 'MONEY', currencyAware: true, percentage: false, precision: 2, unit: null, enabled: true, version: '1' },
  { metricKey: 'estimatedRoyalty', displayName: 'Estimated Royalty', description: 'Estimated royalty amount', category: 'ROYALTY', supportedScopes: ['BOOK', 'PROJECT', 'PORTFOLIO'], supportedDimensions: ['currencyCode'], requiredDataSources: ['canonical_royalties'], aggregationType: 'SUM', valueType: 'MONEY', currencyAware: true, percentage: false, precision: 2, unit: null, enabled: true, version: '1' },
  { metricKey: 'finalizedRoyalty', displayName: 'Finalized Royalty', description: 'Finalized royalty amount', category: 'ROYALTY', supportedScopes: ['BOOK', 'PROJECT', 'PORTFOLIO'], supportedDimensions: ['currencyCode'], requiredDataSources: ['canonical_royalties'], aggregationType: 'SUM', valueType: 'MONEY', currencyAware: true, percentage: false, precision: 2, unit: null, enabled: true, version: '1' },
];
export const bookAnalyticsDefaultPolicy: BookAnalyticsPolicy = { policyVersion: 'book-analytics-default-v1', enabledMetrics: coreAnalyticsMetrics.map((metric) => metric.metricKey), enabledDimensions: ['bookId', 'editionId', 'format', 'providerKey', 'marketplaceId', 'countryCode', 'territoryCode'], defaultReportingCurrency: 'USD', defaultTimezone: 'UTC', defaultAnalyticsPeriod: AnalyticsPeriod.LAST_30_DAYS, weekStartDay: 1, cacheTtlSeconds: 300, batchSize: 500, workerConcurrency: 3, maximumRetries: 3, metricPrecision: 2, includeEstimatedRoyalties: true, preferFinalizedRoyalties: true, snapshotRetentionDays: 1095 };
