import { IsArray, IsBoolean, IsDateString, IsEnum, IsNumber, IsOptional, IsString, Min, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { RoyaltyImportSource, RoyaltyImportStatus, RoyaltyImportTrigger } from '../entities/royalty-ingestion.entity';

export class RoyaltyRecordInputDto { @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() marketplace?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() currency?: string; @IsOptional() @IsString() timezone?: string; @IsString() royaltyPeriod: string; @IsOptional() @IsDateString() paymentDate?: string; @IsOptional() @IsDateString() reportingDate?: string; @IsOptional() @IsString() paymentStatus?: string; @IsOptional() @IsString() royaltyType?: string; @IsOptional() @IsBoolean() estimated?: boolean; @IsOptional() @IsBoolean() finalized?: boolean; @IsOptional() @IsString() bookId?: string; @IsOptional() @IsString() editionId?: string; @IsOptional() @IsString() format?: string; @IsOptional() @IsNumber() @Min(0) unitsSold?: number; @IsOptional() @IsNumber() grossRevenue?: number; @IsOptional() @IsNumber() royaltyRate?: number; @IsNumber() royaltyAmount: number; @IsOptional() @IsNumber() taxAmount?: number; @IsOptional() @IsNumber() withholdingTax?: number; @IsOptional() @IsNumber() paymentAmount?: number; @IsOptional() @IsString() transactionId?: string; @IsOptional() @IsString() externalReference?: string; @IsOptional() metadata?: Record<string, unknown> }
export class ImportRoyaltiesDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsEnum(RoyaltyImportSource) source: RoyaltyImportSource; @IsOptional() @IsEnum(RoyaltyImportTrigger) trigger?: RoyaltyImportTrigger; @IsOptional() @IsString() fileName?: string; @IsOptional() @IsString() fileHash?: string; @IsArray() @ValidateNested({ each: true }) @Type(() => RoyaltyRecordInputDto) records: RoyaltyRecordInputDto[]; @IsOptional() @IsString() idempotencyKey?: string }
export class UploadRoyaltyFileDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsString() fileName: string; @IsString() fileHash: string; @IsEnum(RoyaltyImportSource) source: RoyaltyImportSource; @IsString() content: string }
export class SyncRoyaltiesDto { @IsString() providerKey: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsBoolean() incremental?: boolean; @IsOptional() @IsDateString() since?: string }
export class RoyaltyImportQueryDto { @IsOptional() @IsString() providerKey?: string; @IsOptional() @IsString() projectId?: string; @IsOptional() @IsString() bookId?: string; @IsOptional() @IsString() importId?: string; @IsOptional() @IsEnum(RoyaltyImportStatus) status?: RoyaltyImportStatus; @IsOptional() @Type(() => Number) @Min(1) page = 1; @IsOptional() @Type(() => Number) @Min(1) limit = 25 }
