import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { AIWritingRepository } from '../ai-writing/ai-writing.repository';
import { BookMetadataRepository } from '../book-metadata/book-metadata.repository';
import { BookProjectService } from '../book-project/book-project.service';
import { PublicationReadinessRepository } from '../publication-readiness/publication-readiness.repository';
import { MultiPlatformPublishingPolicy, multiPlatformPublishingDefaultPolicy } from './config/multi-platform-publishing.config';
import type { CreateMultiPlatformPublishingDto, MultiPlatformActionDto, MultiPlatformQueryDto, ResolveConflictDto } from './dto';
import { MultiPlatformEventType, MultiPlatformOrchestrationStatus, MultiPlatformTargetStatus } from './entities/multi-platform-publishing.entity';
import type { MultiPlatformPublishingOrchestrationDocument } from './entities/multi-platform-publishing.entity';
import { MultiPlatformEventRepository } from './multi-platform-event.repository';
import { MultiPlatformPublishingMapper } from './multi-platform-publishing.mapper';
import { MultiPlatformPublishingRepository } from './multi-platform-publishing.repository';
import { MultiPlatformPublishingValidator } from './multi-platform-publishing.validator';
import { MultiPlatformTargetRepository } from './multi-platform-target.repository';
import { PublishingConflictResolver } from './publishing-conflict.resolver';
import { PublishingDependencyResolver } from './publishing-dependency.resolver';
import { PublishingExecutionStrategyFactory } from './publishing-execution-strategy.factory';
import { PublishingPlanBuilder } from './publishing-plan.builder';
import { PublishingResumeCoordinator } from './publishing-resume.coordinator';
import { PublishingRollbackCoordinator } from './publishing-rollback.coordinator';
import { PublishingStatusAggregator } from './publishing-status.aggregator';
import { PublishingTargetResolver } from './publishing-target.resolver';

@Injectable()
export class MultiPlatformPublishingService {
  constructor(private readonly projects: BookProjectService, private readonly contents: AIWritingRepository, private readonly metadata: BookMetadataRepository, private readonly readiness: PublicationReadinessRepository, private readonly orchestrations: MultiPlatformPublishingRepository, private readonly targets: MultiPlatformTargetRepository, private readonly events: MultiPlatformEventRepository, private readonly targetResolver: PublishingTargetResolver, private readonly dependencyResolver: PublishingDependencyResolver, private readonly conflicts: PublishingConflictResolver, private readonly strategy: PublishingExecutionStrategyFactory, private readonly status: PublishingStatusAggregator, private readonly rollback: PublishingRollbackCoordinator, private readonly resumeCoordinator: PublishingResumeCoordinator, private readonly builder: PublishingPlanBuilder, private readonly validator: MultiPlatformPublishingValidator, private readonly mapper: MultiPlatformPublishingMapper) {}
  async create(dto: CreateMultiPlatformPublishingDto, requestedBy: string) {
    const policy = this.policy(dto); await this.projects.findOne(dto.projectId); await this.validateManuscript(dto.projectId, dto.manuscriptVersion);
    const [metadata, readiness] = await Promise.all([this.loadMetadata(dto.projectId), this.readiness.latestAssessment(dto.projectId, dto.manuscriptVersion)]);
    if (!readiness || !['READY', 'READY_WITH_WARNINGS'].includes(readiness.finalDecision)) throw new ConflictException('Approved publication readiness is required for multi-platform publishing');
    const resolved = this.strategy.order(this.targetResolver.resolve(dto.providerKeys, dto.publicationScope, policy), dto.executionStrategy ?? policy.executionStrategy);
    const graph = this.dependencyResolver.graph(resolved); const detectedConflicts = this.conflicts.detect(resolved, metadata); const blockedReasons = this.conflicts.blocked(detectedConflicts, policy.conflictPolicy);
    const fingerprint = this.builder.fingerprint({ projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, publicationScope: dto.publicationScope, providers: resolved, executionStrategy: dto.executionStrategy ?? policy.executionStrategy, policyVersion: policy.policyVersion, metadataVersion: String(metadata.metadataVersion ?? ''), readinessVersion: String(readiness.readinessVersion) });
    const idempotencyKey = dto.idempotencyKey ?? this.builder.idempotencyKey({ projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, publicationScope: dto.publicationScope, fingerprint });
    const existing = await this.orchestrations.findByIdempotencyKey(idempotencyKey); if (existing) return this.mapper.toResponse(existing);
    const active = await this.orchestrations.findActiveOrchestration(dto.projectId, dto.manuscriptVersion, fingerprint); if (active) throw new ConflictException('Active multi-platform publishing orchestration already exists');
    const orchestration = await this.orchestrations.create(this.builder.orchestration(dto, requestedBy, policy, resolved, fingerprint, idempotencyKey, this.normalizeMetadata(metadata), { id: String(readiness._id), version: String(readiness.readinessVersion) }, graph, detectedConflicts, blockedReasons));
    const targetDocs = await Promise.all(resolved.map((target) => this.targets.create(this.builder.target(String(orchestration._id), dto.projectId, target, policy.maximumRetries))));
    await this.orchestrations.update(String(orchestration._id), { providerTargetIds: targetDocs.map((target) => String(target._id)) });
    await this.events.create(this.builder.event(String(orchestration._id), MultiPlatformEventType.ORCHESTRATION_CREATED, 'Multi-platform publishing orchestration created', requestedBy));
    return this.mapper.toResponse((await this.orchestrations.findById(String(orchestration._id)))!);
  }
  async validate(id: string) { const item = await this.document(id); this.validator.validateTransition(item.status, MultiPlatformOrchestrationStatus.VALIDATING); const updated = await this.orchestrations.update(id, { status: item.blockedReasons.length ? MultiPlatformOrchestrationStatus.BLOCKED : MultiPlatformOrchestrationStatus.READY, currentExecutionStage: 'VALIDATED' }); await this.events.create(this.builder.event(id, MultiPlatformEventType.VALIDATION_COMPLETED, 'Multi-platform publishing validation completed', item.requestedBy)); return this.mapper.toResponse(updated!); }
  async queue(id: string) { const item = await this.document(id); this.validator.validateTransition(item.status, MultiPlatformOrchestrationStatus.QUEUED); const updated = await this.orchestrations.update(id, { status: MultiPlatformOrchestrationStatus.QUEUED, queuedAt: new Date() }); await this.events.create(this.builder.event(id, MultiPlatformEventType.ORCHESTRATION_QUEUED, 'Multi-platform publishing orchestration queued', item.requestedBy)); return this.mapper.toResponse(updated!); }
  async start(id: string) { const item = await this.document(id); const startStatus = item.status === MultiPlatformOrchestrationStatus.READY ? MultiPlatformOrchestrationStatus.PROCESSING : item.status; if (startStatus !== item.status) this.validator.validateTransition(item.status, startStatus); await this.orchestrations.update(id, { status: startStatus, startedAt: new Date(), currentExecutionStage: 'EXECUTING' }); const eligible = await this.targets.findEligibleForExecution(id); for (const target of eligible) { await this.targets.update(String(target._id), { status: MultiPlatformTargetStatus.READY_FOR_MANUAL_SUBMISSION, startedAt: new Date(), readyForManualSubmissionAt: new Date(), packageReference: `provider://${target.providerKey}/${target.providerFormat}`, packageFingerprint: `${target.providerKey}:${target.providerFormat}:${item.orchestrationFingerprint}`, checklistReference: `checklist://${target.providerKey}/${target.providerFormat}` }); await this.events.create(this.builder.event(id, MultiPlatformEventType.TARGET_AWAITING_MANUAL_SUBMISSION, 'Provider target awaiting manual submission', item.requestedBy, String(target._id), { providerKey: target.providerKey })); } const updatedTargets = await this.targets.findByOrchestrationId(id); const status = this.status.aggregate(updatedTargets, multiPlatformPublishingDefaultPolicy.partialSuccessPolicy); const updated = await this.orchestrations.update(id, { status, completedAt: status === MultiPlatformOrchestrationStatus.COMPLETED ? new Date() : null }); return this.mapper.toResponse(updated!); }
  async retry(id: string) { const item = await this.document(id); if (![MultiPlatformOrchestrationStatus.FAILED, MultiPlatformOrchestrationStatus.PARTIALLY_COMPLETED, MultiPlatformOrchestrationStatus.RETRY_PENDING].includes(item.status)) throw new ConflictException('Orchestration is not retryable'); const nextRetryAt = new Date(Date.now() + multiPlatformPublishingDefaultPolicy.retryDelayMs * 2 ** item.retryCount); const updated = await this.orchestrations.update(id, { status: MultiPlatformOrchestrationStatus.RETRY_PENDING, retryCount: item.retryCount + 1, nextRetryAt }); await this.events.create(this.builder.event(id, MultiPlatformEventType.RETRY_SCHEDULED, 'Multi-platform publishing retry scheduled', item.requestedBy)); return this.mapper.toResponse(updated!); }
  async retryTarget(orchestrationId: string, targetId: string) { const target = await this.targets.findById(targetId); if (!target || target.orchestrationId !== orchestrationId) throw new NotFoundException('Coordinated target not found'); if (![MultiPlatformTargetStatus.FAILED, MultiPlatformTargetStatus.RETRY_PENDING].includes(target.status)) throw new ConflictException('Target is not retryable'); return this.targets.update(targetId, { status: MultiPlatformTargetStatus.RETRY_PENDING, retryCount: target.retryCount + 1, nextRetryAt: new Date(Date.now() + multiPlatformPublishingDefaultPolicy.retryDelayMs) }); }
  async resume(id: string, userId?: string) { const item = await this.document(id); if (![MultiPlatformOrchestrationStatus.FAILED, MultiPlatformOrchestrationStatus.PARTIALLY_COMPLETED, MultiPlatformOrchestrationStatus.RETRY_PENDING, MultiPlatformOrchestrationStatus.BLOCKED, MultiPlatformOrchestrationStatus.PROCESSING].includes(item.status)) throw new ConflictException('Orchestration cannot be resumed'); await this.resumeCoordinator.eligibleTargets(id); await this.events.create(this.builder.event(id, MultiPlatformEventType.ORCHESTRATION_RESUMED, 'Multi-platform publishing orchestration resumed', userId)); return this.mapper.toResponse((await this.orchestrations.update(id, { status: MultiPlatformOrchestrationStatus.PROCESSING, updatedBy: userId ?? null }))!); }
  async cancel(id: string, dto: MultiPlatformActionDto, userId?: string) { const item = await this.document(id); if ([MultiPlatformOrchestrationStatus.COMPLETED, MultiPlatformOrchestrationStatus.CANCELLED, MultiPlatformOrchestrationStatus.SUPERSEDED].includes(item.status)) throw new ConflictException('Orchestration cannot be cancelled'); await this.rollback.localRollback(id); const updated = await this.orchestrations.update(id, { status: MultiPlatformOrchestrationStatus.CANCELLED, cancelledAt: new Date(), cancellationReason: dto.reason ?? null, updatedBy: userId ?? null }); await this.events.create(this.builder.event(id, MultiPlatformEventType.ORCHESTRATION_CANCELLED, 'Multi-platform publishing orchestration cancelled', userId, undefined, { reason: dto.reason })); return this.mapper.toResponse(updated!); }
  async resolveConflict(id: string, dto: ResolveConflictDto, userId?: string) { const item = await this.document(id); const conflictResolution = { ...item.conflictResolution, [dto.conflictId]: { resolution: dto.resolution, note: dto.note, resolvedBy: userId, resolvedAt: new Date() } }; const blockedReasons = item.blockedReasons.filter((reason) => !reason.includes(dto.conflictId)); await this.events.create(this.builder.event(id, MultiPlatformEventType.CONFLICT_RESOLVED, 'Publishing conflict resolved', userId, undefined, { conflictId: dto.conflictId, resolution: dto.resolution })); return this.mapper.toResponse((await this.orchestrations.update(id, { conflictResolution, blockedReasons, status: blockedReasons.length ? item.status : MultiPlatformOrchestrationStatus.READY }))!); }
  async matrix(id: string) { return (await this.targets.findByOrchestrationId(id)).map((target) => ({ providerKey: target.providerKey, providerFormat: target.providerFormat, required: target.required, priority: target.priority })); }
  async graph(id: string) { const item = await this.document(id); return item.dependencyGraph; }
  async conflictsPreview(id: string) { return (await this.document(id)).conflicts; }
  async targetsFor(id: string) { return this.targets.findByOrchestrationId(id); }
  async eventsFor(id: string) { return this.events.findByOrchestrationId(id); }
  async findById(id: string) { return this.mapper.toResponse(await this.document(id)); }
  async latest(projectId: string, manuscriptVersion?: string) { const item = await this.orchestrations.findLatestOrchestration(projectId, manuscriptVersion); if (!item) throw new NotFoundException('Multi-platform orchestration not found'); return this.mapper.toResponse(item); }
  async findByProjectId(projectId: string) { return (await this.orchestrations.findByProjectId(projectId)).map((item) => this.mapper.toResponse(item)); }
  async search(query: MultiPlatformQueryDto) { const filter: FilterQuery<MultiPlatformPublishingOrchestrationDocument> = {}; if (query.projectId) filter.projectId = query.projectId; if (query.manuscriptVersion) filter.manuscriptVersion = query.manuscriptVersion; if (query.status) filter.status = query.status; const result = await this.orchestrations.paginate(filter, query.page, query.limit); return { ...result, items: result.items.map((item) => this.mapper.toResponse(item)) }; }
  async softDelete(id: string, userId?: string) { if (!(await this.orchestrations.softDelete(id, userId))) throw new NotFoundException('Multi-platform orchestration not found'); }
  async restore(id: string) { const item = await this.orchestrations.restore(id); if (!item) throw new NotFoundException('Deleted multi-platform orchestration not found'); return this.mapper.toResponse(item); }
  private policy(dto: CreateMultiPlatformPublishingDto): MultiPlatformPublishingPolicy { return { ...multiPlatformPublishingDefaultPolicy, policyProfile: dto.policyProfile ?? multiPlatformPublishingDefaultPolicy.policyProfile, executionStrategy: dto.executionStrategy ?? multiPlatformPublishingDefaultPolicy.executionStrategy, partialSuccessPolicy: dto.partialSuccessPolicy ?? multiPlatformPublishingDefaultPolicy.partialSuccessPolicy, failurePolicy: dto.failurePolicy ?? multiPlatformPublishingDefaultPolicy.failurePolicy }; }
  private async validateManuscript(projectId: string, manuscriptVersion: string): Promise<void> { const records = await this.contents.findByProjectId(projectId); if (!records.length) throw new NotFoundException('Manuscript not found'); const actualVersion = records.map((item) => item.contentVersion).join('+'); if (actualVersion !== manuscriptVersion) throw new ConflictException('Manuscript version mismatch'); }
  private async loadMetadata(projectId: string): Promise<Record<string, unknown>> { const metadata = (await this.metadata.findByProjectId(projectId))[0]; if (!metadata) throw new NotFoundException('Book metadata not found'); return metadata.toObject() as unknown as Record<string, unknown>; }
  private normalizeMetadata(metadata: Record<string, unknown>) { return { canonicalTitle: metadata.title, canonicalSubtitle: metadata.subtitle, canonicalAuthorList: [metadata.authorName].filter(Boolean), canonicalEdition: metadata.edition, canonicalLanguage: metadata.language, canonicalIsbnStrategy: metadata.isbn ? 'ISBN' : 'PROVIDER_GENERATED', canonicalSourceMetadataVersion: metadata.metadataVersion }; }
  private async document(id: string): Promise<MultiPlatformPublishingOrchestrationDocument> { const item = await this.orchestrations.findById(id); if (!item) throw new NotFoundException('Multi-platform orchestration not found'); return item; }
}
