import { createHash, randomUUID } from 'crypto';
import { Injectable } from '@nestjs/common';
import type { MultiPlatformPublishingPolicy } from './config/multi-platform-publishing.config';
import type { CreateMultiPlatformPublishingDto } from './dto';
import { MultiPlatformEventType, MultiPlatformOrchestrationStatus, MultiPlatformTargetStatus } from './entities/multi-platform-publishing.entity';
import type { MultiPlatformPublishingOrchestration } from './entities/multi-platform-publishing.entity';
import type { MultiPlatformEvent } from './entities/multi-platform-event.entity';
import type { MultiPlatformTarget } from './entities/multi-platform-target.entity';
import type { DistributionConflict, ResolvedProviderTarget } from './interfaces/multi-platform-publishing.interface';

@Injectable()
export class PublishingPlanBuilder {
  fingerprint(input: { projectId: string; manuscriptVersion: string; publicationScope: string; providers: ResolvedProviderTarget[]; executionStrategy: string; policyVersion: string; metadataVersion?: string; readinessVersion?: string }): string { return createHash('sha256').update(JSON.stringify({ ...input, providers: input.providers.map((provider) => `${provider.providerKey}:${provider.providerFormat}`).sort() })).digest('hex'); }
  idempotencyKey(input: { projectId: string; manuscriptVersion: string; publicationScope: string; fingerprint: string }): string { return createHash('sha256').update(`${input.projectId}:${input.manuscriptVersion}:${input.publicationScope}:${input.fingerprint}`).digest('hex'); }
  orchestration(dto: CreateMultiPlatformPublishingDto, requestedBy: string, policy: MultiPlatformPublishingPolicy, providers: ResolvedProviderTarget[], fingerprint: string, idempotencyKey: string, metadata: Record<string, unknown>, readiness: { id: string | null; version: string | null }, dependencyGraph: Record<string, string[]>, conflicts: DistributionConflict[], blockedReasons: string[]): Partial<MultiPlatformPublishingOrchestration> { return { orchestrationId: `MPO-${randomUUID()}`, projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, publicationScope: dto.publicationScope, providerKeys: providers.map((provider) => provider.providerKey), executionStrategy: dto.executionStrategy ?? policy.executionStrategy, policyProfile: dto.policyProfile ?? policy.policyProfile, policyVersion: policy.policyVersion, idempotencyKey, orchestrationFingerprint: fingerprint, status: blockedReasons.length ? MultiPlatformOrchestrationStatus.BLOCKED : MultiPlatformOrchestrationStatus.READY, normalizedMetadataReference: metadata, publicationReadinessResultId: readiness.id, sourceResultIds: readiness.id ? { PUBLICATION_READINESS: readiness.id } : {}, sourceResultVersions: readiness.version ? { PUBLICATION_READINESS: readiness.version } : {}, providerTargetIds: [], requiredProviderKeys: providers.filter((provider) => provider.required).map((provider) => provider.providerKey), optionalProviderKeys: providers.filter((provider) => !provider.required).map((provider) => provider.providerKey), dependencyGraph, conflicts: conflicts as unknown as Record<string, unknown>[], conflictResolution: {}, blockedReasons, currentExecutionStage: 'PLAN_CREATED', scheduledAt: dto.scheduledAt ? new Date(dto.scheduledAt) : null, queuedAt: null, startedAt: null, completedAt: null, failedAt: null, cancelledAt: null, cancellationReason: null, retryCount: 0, maximumRetries: policy.maximumRetries, nextRetryAt: null, lastError: null, requestedBy, isDeleted: false, deletedAt: null, deletedBy: null, createdBy: requestedBy, updatedBy: requestedBy }; }
  target(orchestrationId: string, projectId: string, target: ResolvedProviderTarget, maximumRetries: number): Partial<MultiPlatformTarget> { return { targetId: `MPT-${randomUUID()}`, orchestrationId, workflowId: null, targetExecutionId: null, projectId, providerKey: target.providerKey, providerFormat: target.providerFormat, required: target.required, priority: target.priority, dependencies: target.dependencies, status: MultiPlatformTargetStatus.READY, packageReference: null, packageFingerprint: null, checklistReference: null, externalSubmissionId: null, externalPublicationId: null, providerStatus: null, providerStatusMessage: null, conflictFlags: [], retryCount: 0, maximumRetries, nextRetryAt: null, startedAt: null, readyForManualSubmissionAt: null, submittedAt: null, publishedAt: null, failedAt: null, cancelledAt: null, lastError: null }; }
  event(orchestrationId: string, eventType: MultiPlatformEventType, message: string, createdBy?: string, targetId?: string, metadata: Record<string, unknown> = {}): Partial<MultiPlatformEvent> { return { eventId: `MPE-${randomUUID()}`, orchestrationId, targetId: targetId ?? null, eventType, message, metadata, createdBy: createdBy ?? null }; }
}
