import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { BookMetadataRepository } from '../book-metadata/book-metadata.repository';
import { ExportRepository } from '../export/export.repository';
import { PublishingTargetExecutionRepository } from '../publishing-workflow/publishing-target-execution.repository';
import type { Draft2DigitalQueryDto, PrepareDraft2DigitalPackageDto, RecordDraft2DigitalSubmissionDto, UpdateDraft2DigitalChecklistItemDto, UpdateDraft2DigitalStatusDto } from './dto';
import { Draft2DigitalChecklistStatus, Draft2DigitalPackage, Draft2DigitalPackageDocument, Draft2DigitalProviderKey, Draft2DigitalStatus } from './entities/draft2digital.entity';
import { draft2DigitalDefaultConfiguration } from './config/draft2digital.config';
import { Draft2DigitalPackageBuilder } from './draft2digital-package.builder';
import { Draft2DigitalRepository } from './draft2digital.repository';
import { Draft2DigitalStatusMapper } from './draft2digital-status.mapper';
import { Draft2DigitalValidator } from './draft2digital.validator';

@Injectable()
export class Draft2DigitalManualSubmissionService {
  constructor(private readonly metadata: BookMetadataRepository, private readonly exports: ExportRepository, private readonly targets: PublishingTargetExecutionRepository, private readonly repository: Draft2DigitalRepository, private readonly builder: Draft2DigitalPackageBuilder, private readonly statusMapper: Draft2DigitalStatusMapper, private readonly validator: Draft2DigitalValidator) {}
  async prepare(dto: PrepareDraft2DigitalPackageDto) {
    const metadata = (await this.metadata.findByProjectId(dto.projectId))[0]; if (!metadata) throw new NotFoundException('Book metadata is required for Draft2Digital package preparation');
    const exportJob = await this.exports.latestExport(dto.projectId);
    const prepared = this.builder.build({ projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, d2dFormat: dto.d2dFormat, metadata: metadata.toObject() as unknown as Record<string, unknown>, exportJob });
    const active = await this.repository.findActivePackage(dto.targetExecutionId, prepared.submissionFingerprint); if (active) return active;
    const latest = await this.repository.findLatestPackage(dto.targetExecutionId);
    return this.repository.create({ packageId: `D2D-${Date.now()}`, workflowId: dto.workflowId, targetExecutionId: dto.targetExecutionId, projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, providerKey: Draft2DigitalProviderKey.DRAFT2DIGITAL, integrationMode: draft2DigitalDefaultConfiguration.integrationMode, d2dFormat: dto.d2dFormat, metadataSnapshot: prepared.metadataSnapshot as unknown as Record<string, unknown>, pricingSnapshot: prepared.pricingSnapshot, artifactReferences: prepared.artifactReferences, coverReferences: prepared.coverReferences, submissionFingerprint: prepared.submissionFingerprint, packageVersion: (latest?.packageVersion ?? 0) + 1, checklistVersion: draft2DigitalDefaultConfiguration.manualChecklistVersion, checklist: prepared.checklist, checklistStatus: Draft2DigitalChecklistStatus.NOT_STARTED, status: prepared.validationIssues.length ? Draft2DigitalStatus.BLOCKED : Draft2DigitalStatus.READY_FOR_SUBMISSION, externalTitleId: null, isbn: prepared.metadataSnapshot.isbn ?? null, externalStatus: null, externalStatusMessage: null, readyForManualSubmissionAt: prepared.validationIssues.length ? null : new Date(), submittedAt: null, publishedAt: null, rejectedAt: null, actionRequiredAt: null, submittedBy: null, lastStatusUpdatedBy: null, sourceResultIds: { metadataId: String(metadata._id), exportJobId: exportJob ? String(exportJob._id) : '' }, validationIssues: prepared.validationIssues, warnings: prepared.warnings, statusHistory: [{ status: prepared.validationIssues.length ? Draft2DigitalStatus.BLOCKED : Draft2DigitalStatus.READY_FOR_SUBMISSION, statusMessage: 'Draft2Digital manual-assisted package prepared. External publishing has not occurred.', recordedAt: new Date(), recordedBy: dto.createdBy ?? null }], isDeleted: false, deletedAt: null, deletedBy: null, createdBy: dto.createdBy ?? null, updatedBy: dto.createdBy ?? null });
  }
  async findById(id: string) { return this.document(id); }
  async latest(targetExecutionId: string) { const item = await this.repository.findLatestPackage(targetExecutionId); if (!item) throw new NotFoundException('Draft2Digital package not found'); return item; }
  async checklist(id: string) { return (await this.document(id)).checklist; }
  async updateChecklistItem(id: string, dto: UpdateDraft2DigitalChecklistItemDto) { const item = await this.document(id); const checklist = item.checklist.map((check) => check.sequence === dto.sequence ? { ...check, completionStatus: dto.completionStatus } : check); const done = checklist.filter((check) => check.completionStatus === Draft2DigitalChecklistStatus.COMPLETED).length; const checklistStatus = done === 0 ? Draft2DigitalChecklistStatus.NOT_STARTED : done === checklist.length ? Draft2DigitalChecklistStatus.COMPLETED : Draft2DigitalChecklistStatus.IN_PROGRESS; return this.repository.update(id, { checklist, checklistStatus }); }
  async recordSubmission(id: string, dto: RecordDraft2DigitalSubmissionDto, userId?: string) { const item = await this.document(id); if (item.status !== Draft2DigitalStatus.READY_FOR_SUBMISSION) throw new ConflictException('Draft2Digital package is not ready for manual submission recording'); if (item.submittedAt) throw new ConflictException('Draft2Digital manual submission is already recorded'); const updated = await this.repository.update(id, { status: Draft2DigitalStatus.SUBMISSION_RECORDED, externalTitleId: this.clean(dto.externalTitleId), isbn: this.clean(dto.isbn) ?? item.isbn, externalStatus: Draft2DigitalStatus.SUBMISSION_RECORDED, externalStatusMessage: this.clean(dto.statusMessage) ?? 'Manual Draft2Digital submission recorded', submittedAt: new Date(), submittedBy: userId ?? dto.submittedBy ?? null, lastStatusUpdatedBy: userId ?? null, $push: { statusHistory: { status: Draft2DigitalStatus.SUBMISSION_RECORDED, statusMessage: 'Manual Draft2Digital submission recorded', recordedAt: new Date(), recordedBy: userId ?? null } } }); await this.syncTarget(updated!); return updated; }
  async updateStatus(id: string, dto: UpdateDraft2DigitalStatusDto, userId?: string) { const item = await this.document(id); this.validator.validateStatusTransition(item.status, dto.status); const dates: Partial<Draft2DigitalPackage> = {}; if (dto.status === Draft2DigitalStatus.LIVE) dates.publishedAt = new Date(); if (dto.status === Draft2DigitalStatus.REJECTED) dates.rejectedAt = new Date(); if (dto.status === Draft2DigitalStatus.ACTION_REQUIRED) dates.actionRequiredAt = new Date(); const updated = await this.repository.update(id, { ...dates, status: dto.status, externalStatus: dto.status, externalStatusMessage: this.clean(dto.statusMessage) ?? null, lastStatusUpdatedBy: userId ?? dto.recordedBy ?? null, $push: { statusHistory: { status: dto.status, statusMessage: this.clean(dto.statusMessage) ?? dto.status, recordedAt: new Date(), recordedBy: userId ?? dto.recordedBy ?? null } } }); await this.syncTarget(updated!); return updated; }
  async history(id: string) { return (await this.document(id)).statusHistory; }
  async search(query: Draft2DigitalQueryDto) { const filter: FilterQuery<Draft2DigitalPackage> = {}; if (query.projectId) filter.projectId = query.projectId; if (query.targetExecutionId) filter.targetExecutionId = query.targetExecutionId; if (query.status) filter.status = query.status; return this.repository.paginate(filter, query.page, query.limit); }
  async softDelete(id: string, userId?: string) { if (!(await this.repository.softDelete(id, userId))) throw new NotFoundException('Draft2Digital package not found'); }
  async restore(id: string) { const item = await this.repository.restore(id); if (!item) throw new NotFoundException('Deleted Draft2Digital package not found'); return item; }
  private async syncTarget(item: Draft2DigitalPackageDocument): Promise<void> { const target = await this.targets.findById(item.targetExecutionId); if (target) await this.targets.update(String(target._id), { status: this.statusMapper.toTargetStatus(item.status), externalSubmissionId: item.externalTitleId ?? target.externalSubmissionId, providerStatus: item.status, providerStatusMessage: item.externalStatusMessage }); }
  private async document(id: string): Promise<Draft2DigitalPackageDocument> { const item = await this.repository.findById(id); if (!item) throw new NotFoundException('Draft2Digital package not found'); return item; }
  private clean(value?: string): string | null { if (!value) return null; return value.replace(/[<>"'`]/g, '').trim() || null; }
}
