import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { BookMetadataRepository } from '../book-metadata/book-metadata.repository';
import { ExportRepository } from '../export/export.repository';
import { PublishingTargetExecutionRepository } from '../publishing-workflow/publishing-target-execution.repository';
import type { GooglePlayBooksQueryDto, PrepareGooglePlayBooksPackageDto, RecordGooglePlayBooksSubmissionDto, UpdateGooglePlayBooksChecklistItemDto, UpdateGooglePlayBooksProcessingStatusDto, UpdateGooglePlayBooksStatusDto } from './dto';
import { googlePlayBooksDefaultConfiguration } from './config/google-play-books.config';
import { GooglePlayBooksChecklistStatus, GooglePlayBooksFileProcessingStatus, GooglePlayBooksPackage, GooglePlayBooksPackageDocument, GooglePlayBooksProviderKey, GooglePlayBooksStatus } from './entities/google-play-books.entity';
import { GooglePlayBooksPackageBuilder } from './google-play-books-package.builder';
import { GooglePlayBooksRepository } from './google-play-books.repository';
import { GooglePlayBooksStatusMapper } from './google-play-books-status.mapper';
import { GooglePlayBooksValidator } from './google-play-books.validator';

@Injectable()
export class GooglePlayBooksManualSubmissionService {
  constructor(private readonly metadata: BookMetadataRepository, private readonly exports: ExportRepository, private readonly targets: PublishingTargetExecutionRepository, private readonly repository: GooglePlayBooksRepository, private readonly builder: GooglePlayBooksPackageBuilder, private readonly statusMapper: GooglePlayBooksStatusMapper, private readonly validator: GooglePlayBooksValidator) {}
  async prepare(dto: PrepareGooglePlayBooksPackageDto) {
    const metadata = (await this.metadata.findByProjectId(dto.projectId))[0]; if (!metadata) throw new NotFoundException('Book metadata is required for Google Play Books package preparation');
    const exportJob = await this.exports.latestExport(dto.projectId);
    const prepared = this.builder.build({ projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, contentFormat: dto.contentFormat, metadata: metadata.toObject() as unknown as Record<string, unknown>, exportJob });
    const active = await this.repository.findActivePackage(dto.targetExecutionId, prepared.submissionFingerprint); if (active) return active;
    const latest = await this.repository.findLatestPackage(dto.targetExecutionId);
    return this.repository.create({ packageId: `GPB-${Date.now()}`, workflowId: dto.workflowId, targetExecutionId: dto.targetExecutionId, projectId: dto.projectId, manuscriptVersion: dto.manuscriptVersion, providerKey: GooglePlayBooksProviderKey.GOOGLE_PLAY_BOOKS, integrationMode: googlePlayBooksDefaultConfiguration.integrationMode, contentFormat: dto.contentFormat, identifierStrategy: prepared.identifierStrategy, isbn: prepared.metadataSnapshot.isbn ?? null, googleBookIdentifier: null, externalBookReference: null, accountProfileReference: googlePlayBooksDefaultConfiguration.accountProfileReference, metadataSnapshot: prepared.metadataSnapshot as unknown as Record<string, unknown>, rightsSnapshot: prepared.rightsSnapshot, territorySnapshot: prepared.territorySnapshot, pricingSnapshot: prepared.pricingSnapshot, previewSnapshot: prepared.previewSnapshot, artifactReferences: prepared.artifactReferences, coverReferences: prepared.coverReferences, submissionFingerprint: prepared.submissionFingerprint, packageVersion: (latest?.packageVersion ?? 0) + 1, checklistVersion: googlePlayBooksDefaultConfiguration.manualChecklistVersion, checklist: prepared.checklist, checklistStatus: GooglePlayBooksChecklistStatus.NOT_STARTED, status: prepared.validationIssues.length ? GooglePlayBooksStatus.BLOCKED : GooglePlayBooksStatus.READY_FOR_SUBMISSION, contentProcessingStatus: GooglePlayBooksFileProcessingStatus.PENDING, coverProcessingStatus: GooglePlayBooksFileProcessingStatus.PENDING, externalStatus: null, externalStatusMessage: null, readyForManualSubmissionAt: prepared.validationIssues.length ? null : new Date(), submittedAt: null, processingStartedAt: null, publishedAt: null, rejectedAt: null, removedAt: null, actionRequiredAt: null, submittedBy: null, lastStatusUpdatedBy: null, sourceResultIds: { metadataId: String(metadata._id), exportJobId: exportJob ? String(exportJob._id) : '' }, validationIssues: prepared.validationIssues, warnings: prepared.warnings, statusHistory: [{ status: prepared.validationIssues.length ? GooglePlayBooksStatus.BLOCKED : GooglePlayBooksStatus.READY_FOR_SUBMISSION, statusMessage: 'Google Play Books manual-assisted package prepared. External submission has not occurred.', recordedAt: new Date(), recordedBy: dto.createdBy ?? null }], processingHistory: [], isDeleted: false, deletedAt: null, deletedBy: null, createdBy: dto.createdBy ?? null, updatedBy: dto.createdBy ?? null });
  }
  async findById(id: string) { return this.document(id); }
  async latest(targetExecutionId: string) { const item = await this.repository.findLatestPackage(targetExecutionId); if (!item) throw new NotFoundException('Google Play Books package not found'); return item; }
  async checklist(id: string) { return (await this.document(id)).checklist; }
  async updateChecklistItem(id: string, dto: UpdateGooglePlayBooksChecklistItemDto) { const item = await this.document(id); const checklist = item.checklist.map((check) => check.sequence === dto.sequence ? { ...check, completionStatus: dto.completionStatus } : check); const done = checklist.filter((check) => check.completionStatus === GooglePlayBooksChecklistStatus.COMPLETED).length; const checklistStatus = done === 0 ? GooglePlayBooksChecklistStatus.NOT_STARTED : done === checklist.length ? GooglePlayBooksChecklistStatus.COMPLETED : GooglePlayBooksChecklistStatus.IN_PROGRESS; return this.repository.update(id, { checklist, checklistStatus }); }
  async recordSubmission(id: string, dto: RecordGooglePlayBooksSubmissionDto, userId?: string) { const item = await this.document(id); if (item.status !== GooglePlayBooksStatus.READY_FOR_SUBMISSION) throw new ConflictException('Google Play Books package is not ready for manual submission recording'); if (item.submittedAt) throw new ConflictException('Google Play Books manual submission is already recorded'); const updated = await this.repository.update(id, { status: GooglePlayBooksStatus.SUBMISSION_RECORDED, accountProfileReference: this.clean(dto.accountProfileReference) ?? item.accountProfileReference, externalBookReference: this.clean(dto.externalBookReference), isbn: this.clean(dto.isbn) ?? item.isbn, googleBookIdentifier: this.clean(dto.googleBookIdentifier), externalStatus: GooglePlayBooksStatus.SUBMISSION_RECORDED, externalStatusMessage: this.clean(dto.statusMessage) ?? 'Manual Google Play Books submission recorded', submittedAt: new Date(), submittedBy: userId ?? dto.submittedBy ?? null, lastStatusUpdatedBy: userId ?? null, $push: { statusHistory: { status: GooglePlayBooksStatus.SUBMISSION_RECORDED, statusMessage: 'Manual Google Play Books submission recorded', recordedAt: new Date(), recordedBy: userId ?? null } } }); await this.syncTarget(updated!); return updated; }
  async updateProcessingStatus(id: string, dto: UpdateGooglePlayBooksProcessingStatusDto, userId?: string) { const item = await this.document(id); const field = dto.fileType.toLowerCase().includes('cover') ? 'coverProcessingStatus' : 'contentProcessingStatus'; this.validator.validateProcessingTransition(item[field], dto.status); const updated = await this.repository.update(id, { [field]: dto.status, processingStartedAt: dto.status === GooglePlayBooksFileProcessingStatus.PROCESSING ? new Date() : item.processingStartedAt, $push: { processingHistory: { status: dto.status, fileType: dto.fileType, statusMessage: this.clean(dto.statusMessage) ?? dto.status, recordedAt: new Date(), recordedBy: userId ?? dto.recordedBy ?? null } } }); return updated; }
  async updateStatus(id: string, dto: UpdateGooglePlayBooksStatusDto, userId?: string) { const item = await this.document(id); this.validator.validateStatusTransition(item.status, dto.status); const dates: Partial<GooglePlayBooksPackage> = {}; if (dto.status === GooglePlayBooksStatus.LIVE) dates.publishedAt = new Date(); if (dto.status === GooglePlayBooksStatus.REJECTED) dates.rejectedAt = new Date(); if (dto.status === GooglePlayBooksStatus.REMOVED) dates.removedAt = new Date(); if (dto.status === GooglePlayBooksStatus.ACTION_REQUIRED) dates.actionRequiredAt = new Date(); const updated = await this.repository.update(id, { ...dates, status: dto.status, externalStatus: dto.status, externalStatusMessage: this.clean(dto.statusMessage) ?? null, lastStatusUpdatedBy: userId ?? dto.recordedBy ?? null, $push: { statusHistory: { status: dto.status, statusMessage: this.clean(dto.statusMessage) ?? dto.status, recordedAt: new Date(), recordedBy: userId ?? dto.recordedBy ?? null } } }); await this.syncTarget(updated!); return updated; }
  async history(id: string) { const item = await this.document(id); return { statusHistory: item.statusHistory, processingHistory: item.processingHistory }; }
  async search(query: GooglePlayBooksQueryDto) { const filter: FilterQuery<GooglePlayBooksPackage> = {}; if (query.projectId) filter.projectId = query.projectId; if (query.targetExecutionId) filter.targetExecutionId = query.targetExecutionId; if (query.status) filter.status = query.status; return this.repository.paginate(filter, query.page, query.limit); }
  async softDelete(id: string, userId?: string) { if (!(await this.repository.softDelete(id, userId))) throw new NotFoundException('Google Play Books package not found'); }
  async restore(id: string) { const item = await this.repository.restore(id); if (!item) throw new NotFoundException('Deleted Google Play Books package not found'); return item; }
  private async syncTarget(item: GooglePlayBooksPackageDocument): Promise<void> { const target = await this.targets.findById(item.targetExecutionId); if (target) await this.targets.update(String(target._id), { status: this.statusMapper.toTargetStatus(item.status), externalSubmissionId: item.externalBookReference ?? target.externalSubmissionId, externalPublicationId: item.googleBookIdentifier ?? target.externalPublicationId, providerStatus: item.status, providerStatusMessage: item.externalStatusMessage }); }
  private async document(id: string): Promise<GooglePlayBooksPackageDocument> { const item = await this.repository.findById(id); if (!item) throw new NotFoundException('Google Play Books package not found'); return item; }
  private clean(value?: string): string | null { if (!value) return null; return value.replace(/[<>"'`]/g, '').trim() || null; }
}
