import { Injectable } from '@nestjs/common';
import { SettingCategory, SettingDataType, SettingScope, SettingVisibility } from './entities/setting.entity';
import type { SettingDefinition } from './interfaces/settings.interface';

const editableScopes = [SettingScope.SYSTEM, SettingScope.ENVIRONMENT, SettingScope.WORKSPACE, SettingScope.PROJECT, SettingScope.USER];
const platformScopes = [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.PROVIDER, SettingScope.MARKETPLACE];

@Injectable()
export class SettingRegistry {
  private readonly definitions = new Map<string, SettingDefinition>([
    ['general.platform_name', { key: 'general.platform_name', category: SettingCategory.GENERAL, displayName: 'Platform name', description: 'Name shown across the platform.', dataType: SettingDataType.STRING, scopes: editableScopes, defaultValue: 'APC Publishing Intelligence', validation: { required: true, minLength: 2, maxLength: 120 }, visibility: SettingVisibility.AUTHENTICATED, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['security.session_timeout', { key: 'security.session_timeout', category: SettingCategory.SECURITY, displayName: 'Session timeout', description: 'Authenticated session timeout duration.', dataType: SettingDataType.DURATION, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE], defaultValue: '30m', validation: { required: true, pattern: '^\\d+[smhd]$' }, requiredPermissions: ['SECURITY_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['notifications.email_enabled', { key: 'notifications.email_enabled', category: SettingCategory.NOTIFICATIONS, displayName: 'Email notifications', description: 'Enable email notification delivery.', dataType: SettingDataType.BOOLEAN, scopes: editableScopes, defaultValue: false, visibility: SettingVisibility.AUTHENTICATED, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['notifications.webhook_signing_secret', { key: 'notifications.webhook_signing_secret', category: SettingCategory.NOTIFICATIONS, displayName: 'Webhook signing secret', description: 'Secret used to sign outgoing notification webhooks.', dataType: SettingDataType.SECRET, scopes: [SettingScope.WORKSPACE, SettingScope.PROVIDER, SettingScope.MARKETPLACE], defaultValue: null, validation: { allowNull: true, minLength: 16 }, requiredPermissions: ['SETTINGS_UPDATE'], visibility: SettingVisibility.SECRET, encrypted: true, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['ai.mock_mode', { key: 'ai.mock_mode', category: SettingCategory.AI, displayName: 'Mock AI mode', description: 'Use mock AI providers for safe validation and tests.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT, SettingScope.WORKSPACE], defaultValue: true, requiredPermissions: ['SETTINGS_UPDATE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['ai.default_model', { key: 'ai.default_model', category: SettingCategory.AI, displayName: 'Default AI model', description: 'Default model identifier for provider-agnostic AI requests.', dataType: SettingDataType.STRING, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT, SettingScope.WORKSPACE, SettingScope.PROVIDER], defaultValue: 'mock-ai', validation: { required: true }, requiredPermissions: ['SETTINGS_UPDATE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['publishing.require_quality_approval', { key: 'publishing.require_quality_approval', category: SettingCategory.PUBLISHING, displayName: 'Require quality approval', description: 'Require quality gates before publishing workflows proceed.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.PROJECT], defaultValue: true, visibility: SettingVisibility.AUTHENTICATED, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['providers.enabled', { key: 'providers.enabled', category: SettingCategory.PROVIDERS, displayName: 'Provider enabled', description: 'Enable or disable a publishing provider.', dataType: SettingDataType.BOOLEAN, scopes: platformScopes, defaultValue: true, requiredPermissions: ['PROVIDER_CONFIGURATION_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['marketplaces.enabled', { key: 'marketplaces.enabled', category: SettingCategory.MARKETPLACES, displayName: 'Marketplace enabled', description: 'Enable or disable marketplace integrations.', dataType: SettingDataType.BOOLEAN, scopes: platformScopes, defaultValue: true, requiredPermissions: ['MARKETPLACE_CONFIGURATION_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['imports.batch_size', { key: 'imports.batch_size', category: SettingCategory.IMPORTS, displayName: 'Import batch size', description: 'Maximum records processed in an import batch.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE], defaultValue: 250, validation: { min: 1, max: 5000 }, visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['synchronization.retry_limit', { key: 'synchronization.retry_limit', category: SettingCategory.SYNCHRONIZATION, displayName: 'Synchronization retry limit', description: 'Retry limit for provider synchronization jobs.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.PROVIDER, SettingScope.MARKETPLACE], defaultValue: 3, validation: { min: 0, max: 10 }, visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['background_jobs.enabled', { key: 'background_jobs.enabled', category: SettingCategory.BACKGROUND_JOBS, displayName: 'Background jobs enabled', description: 'Enable queue-driven background processing.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT, SettingScope.WORKSPACE], defaultValue: true, requiredPermissions: ['SYSTEM_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: true, version: { introducedIn: 'PLC-003' } }],
    ['feature_flags.sales_dashboard', { key: 'feature_flags.sales_dashboard', category: SettingCategory.FEATURE_FLAGS, displayName: 'Sales dashboard', description: 'Enable Sales Dashboard access.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.USER], defaultValue: true, requiredPermissions: ['FEATURE_FLAGS_MANAGE'], visibility: SettingVisibility.AUTHENTICATED, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['feature_flags.ai_insights_dashboard', { key: 'feature_flags.ai_insights_dashboard', category: SettingCategory.FEATURE_FLAGS, displayName: 'AI Insights Dashboard', description: 'Enable AI Insights Dashboard access.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.USER], defaultValue: true, requiredPermissions: ['FEATURE_FLAGS_MANAGE'], visibility: SettingVisibility.AUTHENTICATED, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['storage.default_provider', { key: 'storage.default_provider', category: SettingCategory.STORAGE, displayName: 'Default storage provider', description: 'Default storage backend for generated artifacts.', dataType: SettingDataType.ENUM, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT, SettingScope.WORKSPACE], defaultValue: 'local', allowedValues: ['local', 'minio'], validation: { required: true }, visibility: SettingVisibility.ADMIN, restartRequired: true, version: { introducedIn: 'PLC-003' } }],
    ['monitoring.health_alerts_enabled', { key: 'monitoring.health_alerts_enabled', category: SettingCategory.MONITORING, displayName: 'Health alerts', description: 'Enable health degradation alerts.', dataType: SettingDataType.BOOLEAN, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE], defaultValue: true, visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-003' } }],
    ['performance.pagination_max_limit', { key: 'performance.pagination_max_limit', category: SettingCategory.PERFORMANCE, displayName: 'Maximum pagination limit', description: 'Upper bound for paginated API responses.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE], defaultValue: 100, validation: { min: 10, max: 500 }, requiredPermissions: ['SYSTEM_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-006' } }],
    ['performance.batch_max_size', { key: 'performance.batch_max_size', category: SettingCategory.PERFORMANCE, displayName: 'Maximum batch size', description: 'Upper bound for bounded ingestion and processing batches.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE], defaultValue: 5000, validation: { min: 100, max: 10000 }, requiredPermissions: ['SYSTEM_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-006' } }],
    ['performance.api_slow_threshold_ms', { key: 'performance.api_slow_threshold_ms', category: SettingCategory.PERFORMANCE, displayName: 'Slow API threshold', description: 'Latency threshold used for low-overhead slow request telemetry.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT], defaultValue: 1000, validation: { min: 100, max: 30000 }, requiredPermissions: ['SYSTEM_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-006' } }],
    ['performance.cache_registry_ttl_seconds', { key: 'performance.cache_registry_ttl_seconds', category: SettingCategory.PERFORMANCE, displayName: 'Registry cache TTL', description: 'TTL for stable registry metadata caches.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.ENVIRONMENT], defaultValue: 3600, validation: { min: 60, max: 86400 }, requiredPermissions: ['SYSTEM_SETTINGS_MANAGE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-006' } }],
    ['performance.dashboard_stale_ms', { key: 'performance.dashboard_stale_ms', category: SettingCategory.PERFORMANCE, displayName: 'Dashboard stale time', description: 'Default dashboard query stale time for frontend caching.', dataType: SettingDataType.NUMBER, scopes: [SettingScope.SYSTEM, SettingScope.WORKSPACE, SettingScope.USER], defaultValue: 300000, validation: { min: 5000, max: 3600000 }, requiredPermissions: ['SETTINGS_UPDATE'], visibility: SettingVisibility.ADMIN, restartRequired: false, version: { introducedIn: 'PLC-006' } }],
  ]);

  all() {
    return [...this.definitions.values()];
  }

  categories() {
    return Object.values(SettingCategory);
  }

  find(key: string) {
    return this.definitions.get(key) ?? null;
  }

  byCategory(category?: SettingCategory) {
    return this.all().filter((definition) => !category || definition.category === category);
  }
}
