import type { JobCategory, JobFailureCategory, JobIdempotencyScope, JobOverlapPolicy, JobPayload, JobPriority } from '../entities/background-job.entity';

export interface JobRetryPolicy { attempts: number; delayMs: number; backoff: 'FIXED' | 'EXPONENTIAL'; maxElapsedMs?: number; jitter?: boolean; retryableFailures: JobFailureCategory[]; }
export interface JobConcurrencyPolicy { queue?: number; job?: number; tenant?: number; workspace?: number; provider?: number; marketplace?: number; entity?: number; }
export interface JobRetentionPolicy { succeededMs: number; failedMs: number; deadLetterMs: number; checkpointsMs: number; idempotencyMs: number; eventsMs: number; }
export interface JobNotificationPolicy { completed?: boolean; failed?: boolean; retrying?: boolean; deadLettered?: boolean; repeatedFailures?: boolean; criticalHealth?: boolean; }
export interface JobDefinition<TPayload extends JobPayload = JobPayload> { key: string; displayName: string; description: string; category: JobCategory; queue: string; handlerKey: string; payloadVersion: number; payloadSchema: Record<string, 'string' | 'number' | 'boolean' | 'object' | 'array'>; requiredPermissions: string[]; tenantScoped: boolean; capabilities?: string[]; priority: JobPriority; timeoutMs: number; retryPolicy: JobRetryPolicy; concurrency: JobConcurrencyPolicy; rateLimits?: Record<string, number>; idempotency: { enabled: boolean; scopes: JobIdempotencyScope[] }; cancellationSupported: boolean; checkpointSupported: boolean; scheduleSupported: boolean; retention: JobRetentionPolicy; deadLetter: { enabled: boolean; manualReview: boolean }; notificationPolicy: JobNotificationPolicy; audit: boolean; featureDependency?: string; }
export interface JobContext { executionId: string; tenantId?: string | null; workspaceId?: string | null; projectId?: string | null; providerKey?: string | null; marketplaceKey?: string | null; correlationId?: string | null; cancellationRequested(): Promise<boolean>; checkpoint(data: Record<string, unknown>, progress?: number): Promise<void>; }
export interface JobHandler<TPayload extends JobPayload = JobPayload> { key: string; handle(payload: TPayload, context: JobContext): Promise<Record<string, unknown> | void>; }
