import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { FilterQuery } from 'mongoose';
import { MultiPlatformPublishingRepository } from '../multi-platform-publishing/multi-platform-publishing.repository';
import { MultiPlatformTargetRepository } from '../multi-platform-publishing/multi-platform-target.repository';
import { PublishingTargetExecutionRepository } from '../publishing-workflow/publishing-target-execution.repository';
import { PublishingWorkflowRepository } from '../publishing-workflow/publishing-workflow.repository';
import { BatchSyncPublicationStatusDto, ManualPublicationStatusDto, PublicationStatusSyncQueryDto, ReconcilePublicationStatusDto, ResolvePublicationStatusConflictDto, SyncPublicationStatusDto } from './dto';
import { ProviderSyncStatus, PublicationStatusConflictPolicy, PublicationSyncMode, PublicationSyncTriggerType, PublicationStatusSync } from './entities/publication-status-sync.entity';
import { PublicationStatusHistoryRepository } from './publication-status-history.repository';
import { PublicationStatusScheduler } from './publication-status-scheduler';
import { PublicationStatusSyncEngine } from './publication-status-sync.engine';
import { PublicationStatusSyncRepository } from './publication-status-sync.repository';

@Injectable()
export class PublicationStatusSyncService {
  constructor(private readonly engine: PublicationStatusSyncEngine, private readonly syncs: PublicationStatusSyncRepository, private readonly history: PublicationStatusHistoryRepository, private readonly targets: PublishingTargetExecutionRepository, private readonly workflows: PublishingWorkflowRepository, private readonly multiTargets: MultiPlatformTargetRepository, private readonly orchestrations: MultiPlatformPublishingRepository, private readonly scheduler: PublicationStatusScheduler) {}
  syncTarget(dto: SyncPublicationStatusDto, requestedBy?: string) { return this.engine.syncTarget({ ...dto, triggerType: dto.triggerType ?? PublicationSyncTriggerType.MANUAL, syncMode: dto.syncMode ?? PublicationSyncMode.SINGLE_TARGET }, requestedBy); }
  async syncWorkflow(workflowId: string, requestedBy?: string) { return Promise.all((await this.targets.findByWorkflowId(workflowId)).map((target) => this.syncTarget({ targetExecutionId: String(target._id), triggerType: PublicationSyncTriggerType.MANUAL, syncMode: PublicationSyncMode.SINGLE_WORKFLOW }, requestedBy))); }
  async syncOrchestration(orchestrationId: string, requestedBy?: string) { const targets = await this.multiTargets.findByOrchestrationId(orchestrationId); return Promise.all(targets.filter((target) => target.targetExecutionId).map((target) => this.syncTarget({ targetExecutionId: target.targetExecutionId!, triggerType: PublicationSyncTriggerType.MANUAL, syncMode: PublicationSyncMode.SINGLE_ORCHESTRATION }, requestedBy))); }
  async syncProject(projectId: string, requestedBy?: string) { const result = await this.targets.search({ projectId }, 1, 500); return Promise.all(result.items.map((target) => this.syncTarget({ targetExecutionId: String(target._id), triggerType: PublicationSyncTriggerType.MANUAL, syncMode: PublicationSyncMode.PROJECT }, requestedBy))); }
  async syncProvider(providerKey: string, requestedBy?: string) { return Promise.all((await this.targets.findByProviderKey(providerKey)).map((target) => this.syncTarget({ targetExecutionId: String(target._id), triggerType: PublicationSyncTriggerType.MANUAL, syncMode: PublicationSyncMode.PROVIDER }, requestedBy))); }
  async queueBatch(dto: BatchSyncPublicationStatusDto) { const targets = dto.workflowId ? await this.targets.findByWorkflowId(dto.workflowId) : dto.providerKey ? await this.targets.findByProviderKey(dto.providerKey) : dto.projectId ? (await this.targets.search({ projectId: dto.projectId }, 1, 500)).items : []; return Promise.all(targets.map((target) => this.scheduler.schedule(String(target._id), 0, `publication-status-sync:${String(target._id)}:${dto.triggerType ?? PublicationSyncTriggerType.SCHEDULED}`))); }
  findById(id: string) { return this.syncs.findById(id); }
  latest(targetExecutionId: string) { return this.syncs.findLatestByTarget(targetExecutionId); }
  async search(query: PublicationStatusSyncQueryDto) { const filter: FilterQuery<PublicationStatusSync> = {}; if (query.targetExecutionId) filter.targetExecutionId = query.targetExecutionId; if (query.workflowId) filter.workflowId = query.workflowId; if (query.orchestrationId) filter.orchestrationId = query.orchestrationId; if (query.projectId) filter.projectId = query.projectId; if (query.providerKey) filter.providerKey = query.providerKey; if (query.syncStatus) filter.syncStatus = query.syncStatus; if (query.source) filter.source = query.source; return this.syncs.paginate(filter, query.page, query.limit); }
  async unifiedTargetStatus(targetExecutionId: string) { const [target, latest] = await Promise.all([this.targets.findById(targetExecutionId), this.history.findLatestByTarget(targetExecutionId)]); if (!target) throw new NotFoundException('Publishing target execution not found'); return { targetExecutionId, workflowId: target.workflowId, projectId: target.projectId, providerKey: target.providerKey, providerStatus: target.providerStatus, normalizedStatus: latest?.status ?? null, latestHistory: latest }; }
  async workflowStatus(workflowId: string) { const [workflow, targets, history] = await Promise.all([this.workflows.findById(workflowId), this.targets.findByWorkflowId(workflowId), this.history.findByWorkflowId(workflowId)]); if (!workflow) throw new NotFoundException('Publishing workflow not found'); return { workflowId, status: workflow.status, targetCount: targets.length, latestStatuses: history.slice(0, targets.length) }; }
  async orchestrationStatus(orchestrationId: string) { const [orchestration, targets, history] = await Promise.all([this.orchestrations.findById(orchestrationId), this.multiTargets.findByOrchestrationId(orchestrationId), this.history.findByOrchestrationId(orchestrationId)]); if (!orchestration) throw new NotFoundException('Multi-platform orchestration not found'); return { orchestrationId, status: orchestration.status, targetCount: targets.length, latestStatuses: history.slice(0, targets.length) }; }
  async projectSummary(projectId: string) { const history = await this.history.findByProjectId(projectId); return { projectId, totalStatusEvents: history.length, latestStatuses: history.slice(0, 25) }; }
  historyForTarget(targetExecutionId: string) { return this.history.findByTargetExecutionId(targetExecutionId); }
  manualUpdate(targetExecutionId: string, dto: ManualPublicationStatusDto, requestedBy: string) { return this.engine.manualUpdate(targetExecutionId, dto, requestedBy); }
  privilegedCorrection(targetExecutionId: string, dto: ManualPublicationStatusDto, requestedBy: string) { return this.engine.manualUpdate(targetExecutionId, dto, requestedBy, true); }
  async resolveConflict(id: string, dto: ResolvePublicationStatusConflictDto, userId?: string) { const sync = await this.syncs.findById(id); if (!sync?.conflictDetected) throw new ConflictException('Sync operation has no detected conflict'); return this.syncs.update(id, { conflictResolution: { ...(sync.conflictResolution ?? {}), policy: dto.policy, note: dto.note, resolvedBy: userId, resolvedAt: new Date(), applied: dto.policy !== PublicationStatusConflictPolicy.REQUIRE_MANUAL_REVIEW }, updatedBy: userId ?? null }); }
  async pauseTarget(targetExecutionId: string, userId?: string) { const latest = await this.latest(targetExecutionId); if (!latest) throw new NotFoundException('Sync operation not found'); return this.syncs.update(String(latest._id), { syncStatus: ProviderSyncStatus.PAUSED, updatedBy: userId ?? null }); }
  async resumeTarget(targetExecutionId: string, userId?: string) { const latest = await this.latest(targetExecutionId); if (!latest) throw new NotFoundException('Sync operation not found'); return this.syncs.update(String(latest._id), { syncStatus: ProviderSyncStatus.IDLE, updatedBy: userId ?? null }); }
  async reconcile(dto: ReconcilePublicationStatusDto) { const safeFixes: string[] = []; const unsafeFindings: string[] = []; if (dto.targetExecutionId) { const target = await this.targets.findById(dto.targetExecutionId); const latest = await this.history.findLatestByTarget(dto.targetExecutionId); if (target && latest && target.providerStatus !== latest.status) safeFixes.push('target-status-drift'); if (!target) unsafeFindings.push('missing-target'); } return { projectId: dto.projectId, workflowId: dto.workflowId, orchestrationId: dto.orchestrationId, targetExecutionId: dto.targetExecutionId, safeFixes, unsafeFindings, applied: Boolean(dto.applySafeFixes && safeFixes.length && !unsafeFindings.length) }; }
  async softDelete(id: string, userId?: string) { if (!(await this.syncs.softDelete(id, userId))) throw new NotFoundException('Sync operation not found'); }
  async restore(id: string) { const item = await this.syncs.restore(id); if (!item) throw new NotFoundException('Deleted sync operation not found'); return item; }
}
