import { Brain, Lightbulb } from 'lucide-react';
import type { ReactElement } from 'react';
import type { DashboardDefinition, DashboardFilters, DashboardKey, DashboardScope, DashboardWidgetDefinition } from '@/features/analytics-dashboard/types';
import {
  AcceptedOpportunities,
  AIInsightKPIs,
  AIInsightTrend,
  ExecutiveInsights,
  ExpiringOpportunities,
  GrowthInsights,
  IgnoredOpportunities,
  InProgressOpportunities,
  InsightCategories,
  InsightConfidenceDistribution,
  InsightFreshness,
  MetadataInsights,
  OpportunityCategories,
  OpportunityConfidenceDistribution,
  OpportunityEntityDistribution,
  OpportunityEstimatedImpact,
  OpportunityFreshness,
  OpportunityKPIs,
  OpportunityPriorityDistribution,
  OpportunityQueue,
  OpportunityRecommendations,
  OpportunitySummary,
  OpportunityTrend,
  PerformanceInsights,
  PublishingInsights,
  RecentInsights,
  RecentlyDetectedOpportunities,
  RecentlyUpdatedOpportunities,
  ResolvedOpportunities,
  RiskInsights,
  StaleInsights,
  UserInsights,
} from './components/intelligence-dashboard-sections';

const supportedFilters: DashboardDefinition['supportedFilters'] = ['projectId', 'portfolioId', 'bookIds', 'editionIds', 'authorIds', 'seriesIds', 'providerKeys', 'marketplaceIds', 'countryCodes', 'formats', 'period', 'dateRange', 'comparisonMode', 'comparisonDateRange', 'priorities', 'statuses', 'categories', 'minimumConfidence', 'search'];
const aiInsightScopes: DashboardScope[] = ['PORTFOLIO', 'PROJECT', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'];
const aiInsightDashboards: DashboardKey[] = ['ai-insights-dashboard'];
const aiInsightListWidgets: Array<[string, string, (props: { filters: DashboardFilters }) => ReactElement]> = [
  ['AI_EXECUTIVE_INSIGHTS', 'Executive Insights', ExecutiveInsights],
  ['AI_USER_INSIGHTS', 'User Insights', UserInsights],
  ['AI_GROWTH_INSIGHTS', 'Growth Insights', GrowthInsights],
  ['AI_RISK_INSIGHTS', 'Risk Insights', RiskInsights],
  ['AI_PERFORMANCE_INSIGHTS', 'Performance Insights', PerformanceInsights],
  ['AI_PUBLISHING_INSIGHTS', 'Publishing Insights', PublishingInsights],
  ['AI_METADATA_INSIGHTS', 'Metadata Insights', MetadataInsights],
  ['AI_OPPORTUNITY_RECOMMENDATIONS', 'Opportunity Recommendations', OpportunityRecommendations],
  ['AI_RECENT_INSIGHTS', 'Recent Insights', RecentInsights],
  ['AI_STALE_INSIGHTS', 'Stale Insights', StaleInsights],
];

export const opportunityDashboardWidgets: DashboardWidgetDefinition[] = [
  { key: 'OPPORTUNITY_SUMMARY', type: 'INSIGHT', title: 'Opportunity Summary', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PROJECT', 'PORTFOLIO', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'], queryDefinition: { queryKeyBase: 'opportunity-summary' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunitySummary filters={filters} /> },
  { key: 'OPPORTUNITY_KPIS', type: 'KPI', title: 'Opportunity KPIs', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PROJECT', 'PORTFOLIO', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'], queryDefinition: { queryKeyBase: 'opportunity-kpis' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 1 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityKPIs filters={filters} /> },
  { key: 'OPPORTUNITY_PRIORITY_DISTRIBUTION', type: 'DONUT_CHART', title: 'Priority Distribution', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-priority-distribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV', 'PNG'], version: 1, render: ({ filters }) => <OpportunityPriorityDistribution filters={filters} /> },
  { key: 'OPPORTUNITY_TREND', type: 'TREND_CHART', title: 'Opportunity Trend', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-trend' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV', 'PNG'], version: 1, render: ({ filters }) => <OpportunityTrend filters={filters} /> },
  { key: 'OPPORTUNITY_CATEGORIES', type: 'BREAKDOWN', title: 'Opportunity Categories', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-categories' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityCategories filters={filters} /> },
  { key: 'OPPORTUNITY_ENTITY_DISTRIBUTION', type: 'BREAKDOWN', title: 'Entity Distribution', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-entity-distribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityEntityDistribution filters={filters} /> },
  { key: 'OPPORTUNITY_ESTIMATED_IMPACT', type: 'BREAKDOWN', title: 'Estimated Impact', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-estimated-impact' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityEstimatedImpact filters={filters} /> },
  { key: 'OPPORTUNITY_CONFIDENCE_DISTRIBUTION', type: 'BREAKDOWN', title: 'Confidence Distribution', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-confidence-distribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityConfidenceDistribution filters={filters} /> },
  { key: 'OPPORTUNITY_QUEUE', type: 'TABLE', title: 'Opportunity Queue', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-queue' }, defaultSize: { columns: 12, rows: 4 }, minimumSize: { columns: 6, rows: 3 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityQueue filters={filters} /> },
  { key: 'OPPORTUNITY_RECENTLY_DETECTED', type: 'TABLE', title: 'Recently Detected', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-recently-detected' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentlyDetectedOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_RECENTLY_UPDATED', type: 'TABLE', title: 'Recently Updated', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-recently-updated' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <RecentlyUpdatedOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_ACCEPTED', type: 'TABLE', title: 'Accepted', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-accepted' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <AcceptedOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_IN_PROGRESS', type: 'TABLE', title: 'In Progress', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-in-progress' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <InProgressOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_RESOLVED', type: 'TABLE', title: 'Resolved', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-resolved' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ResolvedOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_IGNORED', type: 'TABLE', title: 'Ignored', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-ignored' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <IgnoredOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_EXPIRING', type: 'ALERT', title: 'Expiring Opportunities', category: 'OPPORTUNITIES', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-expiring' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <ExpiringOpportunities filters={filters} /> },
  { key: 'OPPORTUNITY_FRESHNESS', type: 'HEALTH', title: 'Opportunity Freshness', category: 'OPERATIONS', requiredPermissions: ['opportunities:read'], supportedDashboards: ['opportunity-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'opportunity-freshness' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <OpportunityFreshness filters={filters} /> },
];

export const aiInsightsDashboardWidgets: DashboardWidgetDefinition[] = [
  { key: 'AI_INSIGHT_KPIS', type: 'KPI', title: 'Insight KPIs', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['ai-insights-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'], queryDefinition: { queryKeyBase: 'ai-insight-kpis' }, defaultSize: { columns: 12, rows: 2 }, minimumSize: { columns: 6, rows: 1 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <AIInsightKPIs filters={filters} /> },
  { key: 'AI_INSIGHT_TREND', type: 'TREND_CHART', title: 'Insight Trend', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['ai-insights-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'ai-insight-trend' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV', 'PNG'], version: 1, render: ({ filters }) => <AIInsightTrend filters={filters} /> },
  { key: 'AI_INSIGHT_CATEGORIES', type: 'BREAKDOWN', title: 'Insight Categories', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['ai-insights-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'ai-insight-categories' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <InsightCategories filters={filters} /> },
  { key: 'AI_INSIGHT_CONFIDENCE_DISTRIBUTION', type: 'BREAKDOWN', title: 'Confidence Distribution', category: 'AI_INSIGHTS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['ai-insights-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'ai-insight-confidence-distribution' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <InsightConfidenceDistribution filters={filters} /> },
  ...aiInsightListWidgets.map(([key, title, Component]) => ({ key, type: 'INSIGHT' as const, title, category: 'AI_INSIGHTS' as const, requiredPermissions: ['ai-insights:read'], supportedDashboards: aiInsightDashboards, supportedScopes: aiInsightScopes, queryDefinition: { queryKeyBase: key }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'MANUAL' as const, exportCapabilities: ['CSV' as const], version: 1, render: ({ filters }: { filters: DashboardFilters }) => <Component filters={filters} /> })),
  { key: 'AI_INSIGHT_FRESHNESS', type: 'HEALTH', title: 'Insight Freshness', category: 'OPERATIONS', requiredPermissions: ['ai-insights:read'], supportedDashboards: ['ai-insights-dashboard'], supportedScopes: ['PORTFOLIO', 'PROJECT'], queryDefinition: { queryKeyBase: 'ai-insight-freshness' }, defaultSize: { columns: 6, rows: 3 }, minimumSize: { columns: 4, rows: 2 }, refreshBehavior: 'INHERIT', exportCapabilities: ['CSV'], version: 1, render: ({ filters }) => <InsightFreshness filters={filters} /> },
];

export const opportunityDashboardDefinition: DashboardDefinition = {
  key: 'opportunity-dashboard',
  route: '/analytics/opportunities',
  title: 'Opportunity Dashboard',
  description: 'Review, prioritize, track and understand platform-generated opportunities.',
  icon: Lightbulb,
  category: 'OPPORTUNITIES',
  order: 90,
  enabled: true,
  featureFlag: 'opportunityDashboard',
  requiredPermissions: ['opportunities:read'],
  supportedScopes: ['PROJECT', 'PORTFOLIO', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'],
  defaultScope: 'PORTFOLIO',
  supportedFilters,
  defaultFilters: { scope: 'PORTFOLIO', period: 'LAST_30_DAYS', comparisonMode: 'PREVIOUS_PERIOD', minimumConfidence: 70 },
  supportedPeriods: ['LAST_7_DAYS', 'LAST_30_DAYS', 'LAST_90_DAYS', 'CURRENT_MONTH', 'CURRENT_QUARTER', 'CURRENT_YEAR', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD', 'PREVIOUS_YEAR', 'CUSTOM'],
  defaultComparisonMode: 'PREVIOUS_PERIOD',
  widgetDefinitions: opportunityDashboardWidgets,
  layoutDefinition: {
    columns: 12,
    items: opportunityDashboardWidgets.map((widget, index) => ({ widgetKey: widget.key, colSpan: index < 2 || widget.key === 'OPPORTUNITY_QUEUE' ? 12 : 6, order: index + 1 })),
  },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
};

export const aiInsightsDashboardDefinition: DashboardDefinition = {
  key: 'ai-insights-dashboard',
  route: '/analytics/ai-insights',
  title: 'AI Insights Dashboard',
  description: 'Review validated AI-generated insights, recommendations, warnings and explanations.',
  icon: Brain,
  category: 'AI_INSIGHTS',
  order: 100,
  enabled: true,
  featureFlag: 'aiInsightsDashboard',
  requiredPermissions: ['ai-insights:read'],
  supportedScopes: ['PROJECT', 'PORTFOLIO', 'BOOK', 'EDITION', 'AUTHOR', 'SERIES', 'PROVIDER', 'MARKETPLACE', 'COUNTRY', 'FORMAT'],
  defaultScope: 'PORTFOLIO',
  supportedFilters,
  defaultFilters: { scope: 'PORTFOLIO', period: 'LAST_30_DAYS', comparisonMode: 'NONE', minimumConfidence: 65 },
  supportedPeriods: ['LAST_7_DAYS', 'LAST_30_DAYS', 'LAST_90_DAYS', 'CURRENT_MONTH', 'CURRENT_QUARTER', 'CURRENT_YEAR', 'CUSTOM'],
  defaultPeriod: 'LAST_30_DAYS',
  supportedComparisonModes: ['NONE', 'PREVIOUS_PERIOD', 'PREVIOUS_YEAR', 'CUSTOM'],
  defaultComparisonMode: 'NONE',
  widgetDefinitions: aiInsightsDashboardWidgets,
  layoutDefinition: {
    columns: 12,
    items: aiInsightsDashboardWidgets.map((widget, index) => ({ widgetKey: widget.key, colSpan: index === 0 ? 12 : 6, order: index + 1 })),
  },
  exportCapabilities: ['CSV', 'XLSX'],
  refreshCapabilities: ['DASHBOARD', 'WIDGET', 'VISIBLE_WIDGETS', 'BACKGROUND'],
  savedViewSupport: true,
};
